#pragma once
// Generated by prototype/sst_ms.py (c_source); do not edit.
// Exact fields and manufactured sources of ADR-042's MS-A and MS-B.
#include <algorithm>
#include <cmath>

namespace vibeflow::sst_ms {

inline double Max(double a, double b) { return std::max(a, b); }
inline double Min(double a, double b) { return std::min(a, b); }
inline double Heaviside(double v) { return v > 0 ? 1.0 : (v < 0 ? 0.0 : 0.5); }

inline double k_A(double x, double y, double z) {
  return ((1.0/10.0)*y + 1.0/20.0)*((3.0/10.0)*std::sin(M_PI*x)*std::sin(M_PI*z) + 1);
}
inline double w_A(double x, double y, double z) {
  return (15.0/2.0 - 5.0/2.0*y)*((1.0/5.0)*std::sin(M_PI*x)*std::sin(M_PI*z) + 1);
}
inline double p_A(double x, double y, double z) {
  return (1.0/100.0)*std::cos(M_PI*x)*std::cos(M_PI*y)*std::cos(M_PI*z);
}
inline double u0_A(double x, double y, double z) {
  return (1.0/10.0)*(std::cos(M_PI*y) - std::cos(M_PI*z))*std::sin(M_PI*x);
}
inline double a0_A(double x, double y, double z) {
  return (1.0/10.0)*std::sin(M_PI*y)*std::sin(M_PI*z)/M_PI;
}
inline double u1_A(double x, double y, double z) {
  return (1.0/10.0)*(-std::cos(M_PI*x) + std::cos(M_PI*z))*std::sin(M_PI*y);
}
inline double a1_A(double x, double y, double z) {
  return (1.0/10.0)*std::sin(M_PI*x)*std::sin(M_PI*z)/M_PI;
}
inline double u2_A(double x, double y, double z) {
  return (1.0/10.0)*(std::cos(M_PI*x) - std::cos(M_PI*y))*std::sin(M_PI*z);
}
inline double a2_A(double x, double y, double z) {
  return (1.0/10.0)*std::sin(M_PI*x)*std::sin(M_PI*y)/M_PI;
}
inline double srck_A_2003(double x, double y, double z) {
  const double x0 = M_PI*y;
  const double x1 = std::sin(x0);
  const double x2 = M_PI*x;
  const double x3 = std::cos(x2);
  const double x4 = M_PI*z;
  const double x5 = std::cos(x4);
  const double x6 = -x5;
  const double x7 = -x3 - x6;
  const double x8 = std::sin(x2);
  const double x9 = std::sin(x4);
  const double x10 = x8*x9;
  const double x11 = (3.0/100.0)*x10;
  const double x12 = x11 + 1.0/10.0;
  const double x13 = std::cos(x0);
  const double x14 = -x13 + x3;
  const double x15 = M_PI*x5;
  const double x16 = (1.0/10.0)*y + 1.0/20.0;
  const double x17 = x11*x16;
  const double x18 = x13 + x6;
  const double x19 = M_PI*x3;
  const double x20 = (3.0/10.0)*x10 + 1;
  const double x21 = x16*x20;
  const double x22 = (1.0/5.0)*x10 + 1;
  const double x23 = 15.0/2.0 - 5.0/2.0*y;
  const double x24 = x22*x23;
  const double x25 = x21*x24;
  const double x26 = 0.31*x24;
  const double x27 = std::pow(x7, 2);
  const double x28 = std::pow(x13, 2);
  const double x29 = std::pow(M_PI, 2);
  const double x30 = (1.0/50.0)*x29;
  const double x31 = std::pow(x14, 2);
  const double x32 = std::pow(x5, 2);
  const double x33 = std::pow(x18, 2);
  const double x34 = std::pow(x3, 2);
  const double x35 = x27*x28*x30 + x30*x31*x32 + x30*x33*x34 + 1.0e-300;
  const double x36 = std::sqrt(x35);
  const double x37 = std::pow(y, -2);
  const double x38 = 1.0/x22;
  const double x39 = 1.0/x23;
  const double x40 = x38*x39;
  const double x41 = x37*x40;
  const double x42 = (1.0/40.0)*x41;
  const double x43 = std::sqrt(x21);
  const double x44 = x43/y;
  const double x45 = x40*x44;
  const double x46 = 22.222222222222221*x45;
  const double x47 = std::max(x42, x46);
  const double x48 = std::tanh(std::pow(x47, 2));
  const double x49 = x36*x48;
  const double x50 = std::max(x26, x49);
  const double x51 = 1.0/x50;
  const double x52 = 0.31*x21;
  const double x53 = 11.111111111111111*x45;
  const double x54 = std::max(x42, x53);
  const double x55 = -1.0/2.0*x10 - 5.0/2.0;
  const double x56 = std::pow(x8, 2);
  const double x57 = x32*x56;
  const double x58 = x16*x57;
  const double x59 = x23*x29;
  const double x60 = 0.10271999999999999*x59;
  const double x61 = std::pow(x9, 2);
  const double x62 = x34*x61;
  const double x63 = x16*x62;
  const double x64 = 1.712*x12*x55 + x58*x60 + x60*x63;
  const double x65 = std::max(1.0e-10, x40*x64);
  const double x66 = 1.0/x65;
  const double x67 = 3.4239999999999999*x21;
  const double x68 = std::min(x54, x37*x66*x67);
  const double x69 = std::tanh(std::pow(x68, 4));
  const double x70 = 1.0 - 0.15000000000000002*x69;
  const double x71 = x51*x70;
  const double x72 = x15*x8;
  const double x73 = 0.092999999999999999*x71;
  const double x74 = x26 - x49;
  const double x75 = (((x74 < 0) ? (
   0
)
: ((x74 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x76 = 0.062*x23*x75;
  const double x77 = (((x74 > 0) ? (
   0
)
: ((x74 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x78 = std::pow(M_PI, 3);
  const double x79 = (1.0/50.0)*x78;
  const double x80 = x79*x9;
  const double x81 = x48/x36;
  const double x82 = x39/std::pow(x22, 2);
  const double x83 = x72*x82;
  const double x84 = x37*x83;
  const double x85 = -1.0/40.0*x37*x38*x39;
  const double x86 = x46 + x85;
  const double x87 = (((x86 > 0) ? (
   0
)
: ((x86 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x88 = (1.0/100.0)*x87;
  const double x89 = x44*x83;
  const double x90 = 1.0/x20;
  const double x91 = x45*x90;
  const double x92 = x72*x91;
  const double x93 = 2*(((x86 < 0) ? (
   0
)
: ((x86 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x94 = x36*x47*(1 - std::pow(x48, 2));
  const double x95 = x52*x70/std::pow(x50, 2);
  const double x96 = x53 + x85;
  const double x97 = (((x96 > 0) ? (
   0
)
: ((x96 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x98 = (1.0/200.0)*x97;
  const double x99 = (((x96 < 0) ? (
   0
)
: ((x96 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x100 = -3.4239999999999999*x16*x20*x37*x66 + x54;
  const double x101 = 4*(((x100 > 0) ? (
   0
)
: ((x100 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x102 = (1.0/5.0)*x64;
  const double x103 = 0.85599999999999998*x12;
  const double x104 = 0.20543999999999998*x16*x23*x78;
  const double x105 = x37*x67*(((x38*x39*x64 - 1.0e-10 < 0) ? (
   0
)
: ((x38*x39*x64 - 1.0e-10 == 0) ? (
   1.0/2.0
)
: (
   1
))))/std::pow(x65, 2);
  const double x106 = 4*(((x100 < 0) ? (
   0
)
: ((x100 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x107 = 0.046500000000000007*x21*x51*std::pow(x68, 3)*(1 - std::pow(x69, 2));
  const double x108 = (3.0/10.0)*x16;
  const double x109 = x19*x9;
  const double x110 = x79*x8;
  const double x111 = x109*x82;
  const double x112 = x111*x37;
  const double x113 = x111*x44;
  const double x114 = x109*x91;
  const double x115 = x1*x79;
  const double x116 = std::pow(y, -3);
  const double x117 = x38/std::pow(x23, 2);
  const double x118 = -1.0/20.0*x116*x40 + (1.0/16.0)*x117*x37;
  const double x119 = x41*x43;
  const double x120 = x117*x44;
  const double x121 = x90*((3.0/200.0)*x10 + 1.0/20.0)/x16;
  const double x122 = 0.010272*x59;
  const double x123 = 0.25679999999999997*x29;
  return (1.0/10.0)*x1*x12*x7 + (3.0/5.0)*x10*x16*x29*(x52*x71 + 1.0/20000.0) - x108*x109*(-x107*(x101*(-x112*x98 + x99*(-2.2222222222222223*x113 + 1.6666666666666665*x114)) + x106*(-x105*(-x102*x111 + x40*(-x103*x109 - x104*x3*x61*x8 + 0.20543999999999998*x16*x23*x3*x32*x78*x8 + 0.051359999999999996*M_PI*x3*x55*x9)) + 1.0271999999999999*M_PI*x16*x3*x37*x66*x9)) + x109*x16*x73 + x95*(-x109*x76 - x77*(x81*(-x110*x14*x32 - x110*x3*x33 + (1.0/50.0)*x28*x7*x78*x8) + x94*(-x112*x88 + x93*(-4.4444444444444446*x113 + 3.333333333333333*x114))))) - x108*x72*(-x107*(x101*(-x84*x98 + x99*(-2.2222222222222223*x89 + 1.6666666666666665*x92)) + x106*(-x105*(-x102*x83 + x40*(-x103*x72 - x104*x5*x56*x9 + 0.20543999999999998*x16*x23*x34*x5*x78*x9 + 0.051359999999999996*M_PI*x5*x55*x8)) + 1.0271999999999999*M_PI*x16*x37*x5*x66*x8)) + x16*x72*x73 + x95*(-x72*x76 - x77*(x81*((1.0/50.0)*x18*x34*x78*x9 - x28*x7*x80 - x31*x5*x80) + x94*(-x84*x88 + x93*(-4.4444444444444446*x89 + 3.333333333333333*x92))))) - x12*(-x107*(x101*(x118*x97 + x99*(-11.111111111111111*x119 + 27.777777777777779*x120 + x121*x53)) + x106*(-x105*((5.0/2.0)*x117*x64 + x40*(x122*x57 + x122*x62 - x123*x58 - x123*x63)) - 6.8479999999999999*x116*x21*x66 + 0.34240000000000004*x20*x37*x66)) + 0.031*x20*x71 + x95*(-x75*(-0.15500000000000003*x10 - 0.77500000000000002) - x77*(x81*((1.0/50.0)*x1*x14*x32*x78 - x115*x13*x27 - x115*x18*x34) + x94*(2*x118*x87 + x93*(-22.222222222222221*x119 + 55.555555555555557*x120 + x121*x46))))) + x14*x15*x17 + x17*x18*x19 + 0.089999999999999997*x25 - std::min(0.89999999999999991*x25, x35*x51*x52);
}
inline double srcw_A_2003(double x, double y, double z) {
  const double x0 = M_PI*y;
  const double x1 = std::sin(x0);
  const double x2 = M_PI*x;
  const double x3 = std::cos(x2);
  const double x4 = M_PI*z;
  const double x5 = std::cos(x4);
  const double x6 = -x5;
  const double x7 = -x3 - x6;
  const double x8 = std::sin(x2);
  const double x9 = std::sin(x4);
  const double x10 = x8*x9;
  const double x11 = -1.0/2.0*x10 - 5.0/2.0;
  const double x12 = std::cos(x0);
  const double x13 = -x12 + x3;
  const double x14 = M_PI*x5;
  const double x15 = 15.0/2.0 - 5.0/2.0*y;
  const double x16 = (1.0/50.0)*x10*x15;
  const double x17 = x12 + x6;
  const double x18 = M_PI*x3;
  const double x19 = std::pow(x15, 2);
  const double x20 = (1.0/5.0)*x10 + 1;
  const double x21 = std::pow(x20, 2);
  const double x22 = std::pow(y, -2);
  const double x23 = 1.0/x20;
  const double x24 = 1.0/x15;
  const double x25 = x23*x24;
  const double x26 = x22*x25;
  const double x27 = (1.0/40.0)*x26;
  const double x28 = (1.0/10.0)*y + 1.0/20.0;
  const double x29 = (3.0/10.0)*x10 + 1;
  const double x30 = x28*x29;
  const double x31 = std::sqrt(x30);
  const double x32 = x31/y;
  const double x33 = x25*x32;
  const double x34 = 11.111111111111111*x33;
  const double x35 = std::max(x27, x34);
  const double x36 = (3.0/100.0)*x10 + 1.0/10.0;
  const double x37 = x11*x36;
  const double x38 = std::pow(x5, 2);
  const double x39 = std::pow(x8, 2);
  const double x40 = x38*x39;
  const double x41 = x28*x40;
  const double x42 = std::pow(M_PI, 2);
  const double x43 = x15*x42;
  const double x44 = 0.10271999999999999*x43;
  const double x45 = std::pow(x3, 2);
  const double x46 = std::pow(x9, 2);
  const double x47 = x45*x46;
  const double x48 = x28*x47;
  const double x49 = 1.712*x37 + x41*x44 + x44*x48;
  const double x50 = std::max(1.0e-10, x25*x49);
  const double x51 = 1.0/x50;
  const double x52 = 3.4239999999999999*x30;
  const double x53 = std::min(x35, x22*x51*x52);
  const double x54 = std::tanh(std::pow(x53, 4));
  const double x55 = (3.0/50.0)*x43;
  const double x56 = x15*x20;
  const double x57 = 0.31*x56;
  const double x58 = std::pow(x7, 2);
  const double x59 = std::pow(x12, 2);
  const double x60 = (1.0/50.0)*x42;
  const double x61 = std::pow(x13, 2);
  const double x62 = std::pow(x17, 2);
  const double x63 = x38*x60*x61 + x45*x60*x62 + x58*x59*x60 + 1.0e-300;
  const double x64 = std::sqrt(x63);
  const double x65 = 22.222222222222221*x33;
  const double x66 = std::max(x27, x65);
  const double x67 = std::tanh(std::pow(x66, 2));
  const double x68 = x64*x67;
  const double x69 = std::max(x57, x68);
  const double x70 = 1.0/x69;
  const double x71 = 0.85599999999999998 - 0.35599999999999998*x54;
  const double x72 = x70*x71;
  const double x73 = 0.31*x30;
  const double x74 = 1.0/x29;
  const double x75 = x74/x28;
  const double x76 = x14*x8;
  const double x77 = 0.092999999999999999*x72;
  const double x78 = x15*x76;
  const double x79 = x57 - x68;
  const double x80 = (((x79 < 0) ? (
   0
)
: ((x79 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x81 = 0.062*x80;
  const double x82 = (((x79 > 0) ? (
   0
)
: ((x79 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x83 = std::pow(M_PI, 3);
  const double x84 = (1.0/50.0)*x83;
  const double x85 = x84*x9;
  const double x86 = x67/x64;
  const double x87 = x24/x21;
  const double x88 = x76*x87;
  const double x89 = x22*x88;
  const double x90 = -1.0/40.0*x22*x23*x24;
  const double x91 = x65 + x90;
  const double x92 = (((x91 > 0) ? (
   0
)
: ((x91 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x93 = (1.0/100.0)*x92;
  const double x94 = x32*x88;
  const double x95 = x33*x74;
  const double x96 = x76*x95;
  const double x97 = 2*(((x91 < 0) ? (
   0
)
: ((x91 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x98 = x64*x66*(1 - std::pow(x67, 2));
  const double x99 = x71*x73/std::pow(x69, 2);
  const double x100 = x34 + x90;
  const double x101 = (((x100 > 0) ? (
   0
)
: ((x100 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x102 = (1.0/200.0)*x101;
  const double x103 = (((x100 < 0) ? (
   0
)
: ((x100 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x104 = -3.4239999999999999*x22*x28*x29*x51 + x35;
  const double x105 = 4*(((x104 > 0) ? (
   0
)
: ((x104 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x106 = (1.0/5.0)*x49;
  const double x107 = 0.85599999999999998*x36;
  const double x108 = 0.20543999999999998*x15*x28*x83;
  const double x109 = x22*x52*(((x23*x24*x49 - 1.0e-10 < 0) ? (
   0
)
: ((x23*x24*x49 - 1.0e-10 == 0) ? (
   1.0/2.0
)
: (
   1
))))/std::pow(x50, 2);
  const double x110 = 4*(((x104 < 0) ? (
   0
)
: ((x104 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x111 = 0.11036*x30*std::pow(x53, 3)*x70*(1 - std::pow(x54, 2));
  const double x112 = x18*x9;
  const double x113 = x112*x15;
  const double x114 = x8*x84;
  const double x115 = x112*x87;
  const double x116 = x115*x22;
  const double x117 = x115*x32;
  const double x118 = x112*x95;
  const double x119 = x1*x84;
  const double x120 = std::pow(y, -3);
  const double x121 = x23/x19;
  const double x122 = -1.0/20.0*x120*x25 + (1.0/16.0)*x121*x22;
  const double x123 = x26*x31;
  const double x124 = x121*x32;
  const double x125 = x75*((3.0/200.0)*x10 + 1.0/20.0);
  const double x126 = 0.010272*x43;
  const double x127 = 0.25679999999999997*x42;
  return (1.0/10.0)*x1*x11*x7 + (2.0/5.0)*x10*x43*(x72*x73 + 1.0/20000.0) - x11*(-x111*(x105*(x101*x122 + x103*(-11.111111111111111*x123 + 27.777777777777779*x124 + x125*x34)) + x110*(-x109*((5.0/2.0)*x121*x49 + x25*(x126*x40 + x126*x47 - x127*x41 - x127*x48)) - 6.8479999999999999*x120*x30*x51 + 0.34240000000000004*x22*x29*x51)) + 0.031*x29*x72 + x99*(-x80*(-0.15500000000000003*x10 - 0.77500000000000002) - x82*(x86*((1.0/50.0)*x1*x13*x38*x83 - x119*x12*x58 - x119*x17*x45) + x98*(2*x122*x92 + x97*(-22.222222222222221*x123 + 55.555555555555557*x124 + x125*x65))))) - 1.0/5.0*x113*(-x111*(x105*(-x102*x116 + x103*(-2.2222222222222223*x117 + 1.6666666666666665*x118)) + x110*(-x109*(-x106*x115 + x25*(-x107*x112 - x108*x3*x46*x8 + 0.051359999999999996*M_PI*x11*x3*x9 + 0.20543999999999998*x15*x28*x3*x38*x8*x83)) + 1.0271999999999999*M_PI*x22*x28*x3*x51*x9)) + x112*x28*x77 + x99*(-x113*x81 - x82*(x86*(-x114*x13*x38 - x114*x3*x62 + (1.0/50.0)*x59*x7*x8*x83) + x98*(-x116*x93 + x97*(-4.4444444444444446*x117 + 3.333333333333333*x118))))) + x13*x14*x16 + x16*x17*x18 + x19*x21*(0.082799999999999999 - 0.0078000000000000014*x54) - x25*(1.712 - 1.712*x54)*(x37 + x41*x55 + x48*x55) - 3.2258064516129035*x69*x75*(0.11555555555555558*x54 + 0.44)*std::min(0.89999999999999991*x30*x56, x63*x70*x73) - 1.0/5.0*x78*(-x111*(x105*(-x102*x89 + x103*(-2.2222222222222223*x94 + 1.6666666666666665*x96)) + x110*(-x109*(-x106*x88 + x25*(-x107*x76 - x108*x39*x5*x9 + 0.051359999999999996*M_PI*x11*x5*x8 + 0.20543999999999998*x15*x28*x45*x5*x83*x9)) + 1.0271999999999999*M_PI*x22*x28*x5*x51*x8)) + x28*x76*x77 + x99*(-x78*x81 - x82*(x86*((1.0/50.0)*x17*x45*x83*x9 - x5*x61*x85 - x59*x7*x85) + x98*(-x89*x93 + x97*(-4.4444444444444446*x94 + 3.333333333333333*x96)))));
}
inline double srcu0_A_2003(double x, double y, double z) {
  const double x0 = M_PI*y;
  const double x1 = std::cos(x0);
  const double x2 = M_PI*z;
  const double x3 = std::cos(x2);
  const double x4 = M_PI*x;
  const double x5 = std::sin(x4);
  const double x6 = (1.0/100.0)*M_PI*x5;
  const double x7 = std::cos(x4);
  const double x8 = -x3;
  const double x9 = -x7 - x8;
  const double x10 = -x1 + x7;
  const double x11 = std::sin(x2);
  const double x12 = x1 + x8;
  const double x13 = std::pow(x12, 2);
  const double x14 = x13*x7;
  const double x15 = std::pow(M_PI, 2);
  const double x16 = 15.0/2.0 - 5.0/2.0*y;
  const double x17 = x11*x5;
  const double x18 = (1.0/5.0)*x17 + 1;
  const double x19 = 0.31*x16*x18;
  const double x20 = std::pow(x1, 2);
  const double x21 = (1.0/50.0)*x15;
  const double x22 = std::pow(x3, 2);
  const double x23 = std::sqrt(std::pow(x10, 2)*x21*x22 + x13*x21*std::pow(x7, 2) + x20*x21*std::pow(x9, 2) + 1.0e-300);
  const double x24 = std::pow(y, -2);
  const double x25 = 1.0/x16;
  const double x26 = x25/x18;
  const double x27 = (1.0/40.0)*x24*x26;
  const double x28 = (1.0/10.0)*y + 1.0/20.0;
  const double x29 = (3.0/10.0)*x17 + 1;
  const double x30 = x28*x29;
  const double x31 = std::sqrt(x30)/y;
  const double x32 = x26*x31;
  const double x33 = 22.222222222222221*x32;
  const double x34 = std::max(x27, x33);
  const double x35 = std::tanh(std::pow(x34, 2));
  const double x36 = std::max(x19, x23*x35);
  const double x37 = 1.0/x36;
  const double x38 = 0.31*x30;
  const double x39 = (1.0/5.0)*x12;
  const double x40 = M_PI*x7;
  const double x41 = x11*x40;
  const double x42 = x19 - x23*x35;
  const double x43 = std::pow(M_PI, 3);
  const double x44 = (1.0/50.0)*x43*x5;
  const double x45 = -x27 + x33;
  const double x46 = x25*x41/std::pow(x18, 2);
  return -x1*x3*x6 + x10*std::pow(x11, 2)*x6 + x14*x6 + x15*x39*x5*(x37*x38 + 1.0/20000.0) - x39*x40*(0.092999999999999999*x28*x37*x41 + x38*(-0.062*x16*x41*(((x42 < 0) ? (
   0
)
: ((x42 == 0) ? (
   1.0/2.0
)
: (
   1
)))) - (x23*x34*(1 - std::pow(x35, 2))*(-1.0/100.0*x24*x46*(((x45 > 0) ? (
   0
)
: ((x45 == 0) ? (
   1.0/2.0
)
: (
   1
)))) + 2*(-4.4444444444444446*x31*x46 + 3.333333333333333*x32*x41/x29)*(((x45 < 0) ? (
   0
)
: ((x45 == 0) ? (
   1.0/2.0
)
: (
   1
))))) + x35*(-x10*x22*x44 - x14*x44 + (1.0/50.0)*x20*x43*x5*x9)/x23)*(((x42 > 0) ? (
   0
)
: ((x42 == 0) ? (
   1.0/2.0
)
: (
   1
)))))/std::pow(x36, 2)) - x6*x9*std::pow(std::sin(x0), 2);
}
inline double srcu1_A_2003(double x, double y, double z) {
  const double x0 = M_PI*x;
  const double x1 = std::cos(x0);
  const double x2 = M_PI*z;
  const double x3 = std::cos(x2);
  const double x4 = M_PI*y;
  const double x5 = std::sin(x4);
  const double x6 = (1.0/100.0)*M_PI*x5;
  const double x7 = -x3;
  const double x8 = -x1 - x7;
  const double x9 = std::pow(x8, 2);
  const double x10 = std::cos(x4);
  const double x11 = x10*x9;
  const double x12 = x1 - x10;
  const double x13 = std::sin(x2);
  const double x14 = x10 + x7;
  const double x15 = std::sin(x0);
  const double x16 = std::pow(M_PI, 2);
  const double x17 = 15.0/2.0 - 5.0/2.0*y;
  const double x18 = x13*x15;
  const double x19 = (1.0/5.0)*x18 + 1;
  const double x20 = 0.31*x17*x19;
  const double x21 = (1.0/50.0)*x16;
  const double x22 = std::pow(x3, 2);
  const double x23 = std::pow(x1, 2);
  const double x24 = std::sqrt(std::pow(x10, 2)*x21*x9 + std::pow(x12, 2)*x21*x22 + std::pow(x14, 2)*x21*x23 + 1.0e-300);
  const double x25 = std::pow(y, -2);
  const double x26 = 1.0/x19;
  const double x27 = 1.0/x17;
  const double x28 = x26*x27;
  const double x29 = x25*x28;
  const double x30 = (1.0/10.0)*y + 1.0/20.0;
  const double x31 = (3.0/10.0)*x18 + 1;
  const double x32 = x30*x31;
  const double x33 = std::sqrt(x32);
  const double x34 = x33/y;
  const double x35 = 22.222222222222221*x28*x34;
  const double x36 = std::max(x35, (1.0/40.0)*x29);
  const double x37 = std::tanh(std::pow(x36, 2));
  const double x38 = x24*x37;
  const double x39 = std::max(x20, x38);
  const double x40 = 1.0/x39;
  const double x41 = 0.31*x32;
  const double x42 = (1.0/5.0)*x8;
  const double x43 = x20 - x38;
  const double x44 = std::pow(M_PI, 3);
  const double x45 = (1.0/50.0)*x44*x5;
  const double x46 = x26/std::pow(x17, 2);
  const double x47 = -1.0/40.0*x25*x26*x27 + x35;
  return -x1*x3*x6 - M_PI*x10*x42*(0.031*x31*x40 + x41*(-(-0.15500000000000003*x18 - 0.77500000000000002)*(((x43 < 0) ? (
   0
)
: ((x43 == 0) ? (
   1.0/2.0
)
: (
   1
)))) - (x24*x36*(1 - std::pow(x37, 2))*(2*((1.0/16.0)*x25*x46 - 1.0/20.0*x28/std::pow(y, 3))*(((x47 > 0) ? (
   0
)
: ((x47 == 0) ? (
   1.0/2.0
)
: (
   1
)))) + 2*(-22.222222222222221*x29*x33 + 55.555555555555557*x34*x46 + x35*((3.0/200.0)*x18 + 1.0/20.0)/(x30*x31))*(((x47 < 0) ? (
   0
)
: ((x47 == 0) ? (
   1.0/2.0
)
: (
   1
))))) + x37*(-x11*x45 + (1.0/50.0)*x12*x22*x44*x5 - x14*x23*x45)/x24)*(((x43 > 0) ? (
   0
)
: ((x43 == 0) ? (
   1.0/2.0
)
: (
   1
)))))/std::pow(x39, 2)) + x11*x6 - x12*std::pow(x13, 2)*x6 + x14*std::pow(x15, 2)*x6 + x16*x42*x5*(x40*x41 + 1.0/20000.0);
}
inline double srcu2_A_2003(double x, double y, double z) {
  const double x0 = M_PI*x;
  const double x1 = std::cos(x0);
  const double x2 = M_PI*y;
  const double x3 = std::cos(x2);
  const double x4 = M_PI*z;
  const double x5 = std::sin(x4);
  const double x6 = (1.0/100.0)*M_PI*x5;
  const double x7 = std::cos(x4);
  const double x8 = -x7;
  const double x9 = -x1 - x8;
  const double x10 = x1 - x3;
  const double x11 = std::pow(x10, 2);
  const double x12 = x11*x7;
  const double x13 = x3 + x8;
  const double x14 = std::sin(x0);
  const double x15 = std::pow(M_PI, 2);
  const double x16 = 15.0/2.0 - 5.0/2.0*y;
  const double x17 = x14*x5;
  const double x18 = (1.0/5.0)*x17 + 1;
  const double x19 = 0.31*x16*x18;
  const double x20 = std::pow(x3, 2);
  const double x21 = (1.0/50.0)*x15;
  const double x22 = std::pow(x1, 2);
  const double x23 = std::sqrt(x11*x21*std::pow(x7, 2) + std::pow(x13, 2)*x21*x22 + x20*x21*std::pow(x9, 2) + 1.0e-300);
  const double x24 = std::pow(y, -2);
  const double x25 = 1.0/x16;
  const double x26 = x25/x18;
  const double x27 = (1.0/40.0)*x24*x26;
  const double x28 = (1.0/10.0)*y + 1.0/20.0;
  const double x29 = (3.0/10.0)*x17 + 1;
  const double x30 = x28*x29;
  const double x31 = std::sqrt(x30)/y;
  const double x32 = x26*x31;
  const double x33 = 22.222222222222221*x32;
  const double x34 = std::max(x27, x33);
  const double x35 = std::tanh(std::pow(x34, 2));
  const double x36 = std::max(x19, x23*x35);
  const double x37 = 1.0/x36;
  const double x38 = 0.31*x30;
  const double x39 = (1.0/5.0)*x10;
  const double x40 = M_PI*x7;
  const double x41 = x14*x40;
  const double x42 = x19 - x23*x35;
  const double x43 = std::pow(M_PI, 3);
  const double x44 = (1.0/50.0)*x43*x5;
  const double x45 = -x27 + x33;
  const double x46 = x25*x41/std::pow(x18, 2);
  return -x1*x3*x6 + x12*x6 - x13*std::pow(x14, 2)*x6 + x15*x39*x5*(x37*x38 + 1.0/20000.0) - x39*x40*(0.092999999999999999*x28*x37*x41 + x38*(-0.062*x16*x41*(((x42 < 0) ? (
   0
)
: ((x42 == 0) ? (
   1.0/2.0
)
: (
   1
)))) - (x23*x34*(1 - std::pow(x35, 2))*(-1.0/100.0*x24*x46*(((x45 > 0) ? (
   0
)
: ((x45 == 0) ? (
   1.0/2.0
)
: (
   1
)))) + 2*(-4.4444444444444446*x31*x46 + 3.333333333333333*x32*x41/x29)*(((x45 < 0) ? (
   0
)
: ((x45 == 0) ? (
   1.0/2.0
)
: (
   1
))))) + x35*(-x12*x44 + (1.0/50.0)*x13*x22*x43*x5 - x20*x44*x9)/x23)*(((x42 > 0) ? (
   0
)
: ((x42 == 0) ? (
   1.0/2.0
)
: (
   1
)))))/std::pow(x36, 2)) + x6*x9*std::pow(std::sin(x2), 2);
}
inline double srck_A_1994(double x, double y, double z) {
  const double x0 = M_PI*y;
  const double x1 = std::sin(x0);
  const double x2 = M_PI*x;
  const double x3 = std::cos(x2);
  const double x4 = M_PI*z;
  const double x5 = std::cos(x4);
  const double x6 = -x5;
  const double x7 = -x3 - x6;
  const double x8 = std::sin(x2);
  const double x9 = std::sin(x4);
  const double x10 = x8*x9;
  const double x11 = (3.0/100.0)*x10;
  const double x12 = x11 + 1.0/10.0;
  const double x13 = std::cos(x0);
  const double x14 = -x13 + x3;
  const double x15 = M_PI*x5;
  const double x16 = (1.0/10.0)*y + 1.0/20.0;
  const double x17 = x11*x16;
  const double x18 = x13 + x6;
  const double x19 = M_PI*x3;
  const double x20 = (3.0/10.0)*x10 + 1;
  const double x21 = x16*x20;
  const double x22 = (1.0/5.0)*x10 + 1;
  const double x23 = 15.0/2.0 - 5.0/2.0*y;
  const double x24 = x22*x23;
  const double x25 = x21*x24;
  const double x26 = 0.31*x24;
  const double x27 = std::pow(x1, 2);
  const double x28 = std::pow(M_PI, 2);
  const double x29 = std::pow(x8, 2);
  const double x30 = (1.0/25.0)*x29;
  const double x31 = x28*x30;
  const double x32 = std::pow(x9, 2);
  const double x33 = (1.0/25.0)*x32;
  const double x34 = std::sqrt(x27*x28*x33 + x27*x31 + x31*x32 + 1.0e-300);
  const double x35 = std::pow(y, -2);
  const double x36 = 1.0/x22;
  const double x37 = 1.0/x23;
  const double x38 = x36*x37;
  const double x39 = x35*x38;
  const double x40 = (1.0/40.0)*x39;
  const double x41 = std::sqrt(x21);
  const double x42 = x41/y;
  const double x43 = x38*x42;
  const double x44 = 22.222222222222221*x43;
  const double x45 = std::max(x40, x44);
  const double x46 = std::tanh(std::pow(x45, 2));
  const double x47 = x34*x46;
  const double x48 = std::max(x26, x47);
  const double x49 = 1.0/x48;
  const double x50 = (1.0/50.0)*x28;
  const double x51 = std::pow(x5, 2);
  const double x52 = std::pow(x3, 2);
  const double x53 = 0.31*x21;
  const double x54 = 11.111111111111111*x43;
  const double x55 = std::max(x40, x54);
  const double x56 = -1.0/2.0*x10 - 5.0/2.0;
  const double x57 = x29*x51;
  const double x58 = x16*x57;
  const double x59 = x23*x28;
  const double x60 = 0.10271999999999999*x59;
  const double x61 = x32*x52;
  const double x62 = x16*x61;
  const double x63 = 1.712*x12*x56 + x58*x60 + x60*x62;
  const double x64 = std::max(9.9999999999999995e-21, x38*x63);
  const double x65 = 1.0/x64;
  const double x66 = 3.4239999999999999*x21;
  const double x67 = std::min(x55, x35*x65*x66);
  const double x68 = std::tanh(std::pow(x67, 4));
  const double x69 = 1.0 - 0.15000000000000002*x68;
  const double x70 = x49*x69;
  const double x71 = x15*x8;
  const double x72 = 0.092999999999999999*x70;
  const double x73 = x26 - x47;
  const double x74 = (((x73 < 0) ? (
   0
)
: ((x73 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x75 = 0.062*x23*x74;
  const double x76 = (((x73 > 0) ? (
   0
)
: ((x73 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x77 = std::pow(M_PI, 3);
  const double x78 = x30*x77;
  const double x79 = x5*x9;
  const double x80 = x77*x79;
  const double x81 = (1.0/25.0)*x27;
  const double x82 = x46/x34;
  const double x83 = x37/std::pow(x22, 2);
  const double x84 = x71*x83;
  const double x85 = x35*x84;
  const double x86 = -1.0/40.0*x35*x36*x37;
  const double x87 = x44 + x86;
  const double x88 = (((x87 > 0) ? (
   0
)
: ((x87 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x89 = (1.0/100.0)*x88;
  const double x90 = x42*x84;
  const double x91 = 1.0/x20;
  const double x92 = x43*x91;
  const double x93 = x71*x92;
  const double x94 = 2*(((x87 < 0) ? (
   0
)
: ((x87 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x95 = x34*x45*(1 - std::pow(x46, 2));
  const double x96 = x53*x69/std::pow(x48, 2);
  const double x97 = x54 + x86;
  const double x98 = (((x97 > 0) ? (
   0
)
: ((x97 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x99 = (1.0/200.0)*x98;
  const double x100 = (((x97 < 0) ? (
   0
)
: ((x97 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x101 = -3.4239999999999999*x16*x20*x35*x65 + x55;
  const double x102 = 4*(((x101 > 0) ? (
   0
)
: ((x101 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x103 = (1.0/5.0)*x63;
  const double x104 = 0.85599999999999998*x12;
  const double x105 = 0.20543999999999998*x16*x23;
  const double x106 = x35*x66*(((x36*x37*x63 - 9.9999999999999995e-21 < 0) ? (
   0
)
: ((x36*x37*x63 - 9.9999999999999995e-21 == 0) ? (
   1.0/2.0
)
: (
   1
))))/std::pow(x64, 2);
  const double x107 = 4*(((x101 < 0) ? (
   0
)
: ((x101 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x108 = 0.046500000000000007*x21*x49*std::pow(x67, 3)*(1 - std::pow(x68, 2));
  const double x109 = (3.0/10.0)*x16;
  const double x110 = x19*x9;
  const double x111 = x3*x8;
  const double x112 = x111*x77;
  const double x113 = x33*x77;
  const double x114 = x110*x83;
  const double x115 = x114*x35;
  const double x116 = x114*x42;
  const double x117 = x110*x92;
  const double x118 = x1*x13;
  const double x119 = std::pow(y, -3);
  const double x120 = x36/std::pow(x23, 2);
  const double x121 = -1.0/20.0*x119*x38 + (1.0/16.0)*x120*x35;
  const double x122 = x39*x41;
  const double x123 = x120*x42;
  const double x124 = x91*((3.0/200.0)*x10 + 1.0/20.0)/x16;
  const double x125 = 0.010272*x59;
  const double x126 = 0.25679999999999997*x28;
  return (1.0/10.0)*x1*x12*x7 + (3.0/5.0)*x10*x16*x28*(x53*x70 + 1.0/20000.0) - x109*x110*(-x108*(x102*(x100*(-2.2222222222222223*x116 + 1.6666666666666665*x117) - x115*x99) + x107*(-x106*(-x103*x114 + x38*(-x104*x110 - x105*x112*x32 + 0.20543999999999998*x16*x23*x3*x51*x77*x8 + 0.051359999999999996*M_PI*x3*x56*x9)) + 1.0271999999999999*M_PI*x16*x3*x35*x65*x9)) + x110*x16*x72 + x96*(-x110*x75 - x76*(x82*(x111*x113 + x112*x81) + x95*(-x115*x89 + x94*(-4.4444444444444446*x116 + 3.333333333333333*x117))))) - x109*x71*(-x108*(x102*(x100*(-2.2222222222222223*x90 + 1.6666666666666665*x93) - x85*x99) + x107*(-x106*(-x103*x84 + x38*(-x104*x71 - x105*x29*x80 + 0.20543999999999998*x16*x23*x5*x52*x77*x9 + 0.051359999999999996*M_PI*x5*x56*x8)) + 1.0271999999999999*M_PI*x16*x35*x5*x65*x8)) + x16*x71*x72 + x96*(-x71*x75 - x76*(x82*(x78*x79 + x80*x81) + x95*(-x85*x89 + x94*(-4.4444444444444446*x90 + 3.333333333333333*x93))))) - x12*(-x108*(x102*(x100*(-11.111111111111111*x122 + 27.777777777777779*x123 + x124*x54) + x121*x98) + x107*(-x106*((5.0/2.0)*x120*x63 + x38*(x125*x57 + x125*x61 - x126*x58 - x126*x62)) - 6.8479999999999999*x119*x21*x65 + 0.34240000000000004*x20*x35*x65)) + 0.031*x20*x70 + x96*(-x74*(-0.15500000000000003*x10 - 0.77500000000000002) - x76*(x82*(x113*x118 + x118*x78) + x95*(2*x121*x88 + x94*(-22.222222222222221*x122 + 55.555555555555557*x123 + x124*x44))))) + x14*x15*x17 + x17*x18*x19 + 0.089999999999999997*x25 - std::min(1.7999999999999998*x25, x49*x53*(std::pow(x13, 2)*x50*std::pow(x7, 2) + std::pow(x14, 2)*x50*x51 + std::pow(x18, 2)*x50*x52 + 1.0e-300));
}
inline double srcw_A_1994(double x, double y, double z) {
  const double x0 = M_PI*y;
  const double x1 = std::sin(x0);
  const double x2 = M_PI*x;
  const double x3 = std::cos(x2);
  const double x4 = M_PI*z;
  const double x5 = std::cos(x4);
  const double x6 = -x5;
  const double x7 = -x3 - x6;
  const double x8 = std::sin(x2);
  const double x9 = std::sin(x4);
  const double x10 = x8*x9;
  const double x11 = -1.0/2.0*x10 - 5.0/2.0;
  const double x12 = std::cos(x0);
  const double x13 = -x12 + x3;
  const double x14 = M_PI*x5;
  const double x15 = 15.0/2.0 - 5.0/2.0*y;
  const double x16 = (1.0/50.0)*x10*x15;
  const double x17 = x12 + x6;
  const double x18 = M_PI*x3;
  const double x19 = std::pow(x15, 2);
  const double x20 = (1.0/5.0)*x10 + 1;
  const double x21 = std::pow(x20, 2);
  const double x22 = std::pow(y, -2);
  const double x23 = 1.0/x20;
  const double x24 = 1.0/x15;
  const double x25 = x23*x24;
  const double x26 = x22*x25;
  const double x27 = (1.0/40.0)*x26;
  const double x28 = (1.0/10.0)*y + 1.0/20.0;
  const double x29 = (3.0/10.0)*x10 + 1;
  const double x30 = x28*x29;
  const double x31 = std::sqrt(x30);
  const double x32 = x31/y;
  const double x33 = x25*x32;
  const double x34 = 11.111111111111111*x33;
  const double x35 = std::max(x27, x34);
  const double x36 = (3.0/100.0)*x10 + 1.0/10.0;
  const double x37 = x11*x36;
  const double x38 = std::pow(x8, 2);
  const double x39 = std::pow(x5, 2);
  const double x40 = x38*x39;
  const double x41 = x28*x40;
  const double x42 = std::pow(M_PI, 2);
  const double x43 = x15*x42;
  const double x44 = 0.10271999999999999*x43;
  const double x45 = std::pow(x9, 2);
  const double x46 = std::pow(x3, 2);
  const double x47 = x45*x46;
  const double x48 = x28*x47;
  const double x49 = 1.712*x37 + x41*x44 + x44*x48;
  const double x50 = std::max(9.9999999999999995e-21, x25*x49);
  const double x51 = 1.0/x50;
  const double x52 = 3.4239999999999999*x30;
  const double x53 = std::min(x35, x22*x51*x52);
  const double x54 = std::tanh(std::pow(x53, 4));
  const double x55 = (1.0/50.0)*x42;
  const double x56 = (3.0/50.0)*x43;
  const double x57 = 0.31*x15*x20;
  const double x58 = std::pow(x1, 2);
  const double x59 = (1.0/25.0)*x38;
  const double x60 = x42*x59;
  const double x61 = (1.0/25.0)*x45;
  const double x62 = std::sqrt(x42*x58*x61 + x45*x60 + x58*x60 + 1.0e-300);
  const double x63 = 22.222222222222221*x33;
  const double x64 = std::max(x27, x63);
  const double x65 = std::tanh(std::pow(x64, 2));
  const double x66 = x62*x65;
  const double x67 = std::max(x57, x66);
  const double x68 = 1.0/x67;
  const double x69 = 0.85599999999999998 - 0.35599999999999998*x54;
  const double x70 = x68*x69;
  const double x71 = 0.31*x30;
  const double x72 = x14*x8;
  const double x73 = 0.092999999999999999*x70;
  const double x74 = x15*x72;
  const double x75 = x57 - x66;
  const double x76 = (((x75 < 0) ? (
   0
)
: ((x75 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x77 = 0.062*x76;
  const double x78 = (((x75 > 0) ? (
   0
)
: ((x75 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x79 = std::pow(M_PI, 3);
  const double x80 = x59*x79;
  const double x81 = x5*x9;
  const double x82 = x79*x81;
  const double x83 = (1.0/25.0)*x58;
  const double x84 = x65/x62;
  const double x85 = x24/x21;
  const double x86 = x72*x85;
  const double x87 = x22*x86;
  const double x88 = -1.0/40.0*x22*x23*x24;
  const double x89 = x63 + x88;
  const double x90 = (((x89 > 0) ? (
   0
)
: ((x89 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x91 = (1.0/100.0)*x90;
  const double x92 = x32*x86;
  const double x93 = 1.0/x29;
  const double x94 = x33*x93;
  const double x95 = x72*x94;
  const double x96 = 2*(((x89 < 0) ? (
   0
)
: ((x89 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x97 = x62*x64*(1 - std::pow(x65, 2));
  const double x98 = x69*x71/std::pow(x67, 2);
  const double x99 = x34 + x88;
  const double x100 = (((x99 > 0) ? (
   0
)
: ((x99 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x101 = (1.0/200.0)*x100;
  const double x102 = (((x99 < 0) ? (
   0
)
: ((x99 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x103 = -3.4239999999999999*x22*x28*x29*x51 + x35;
  const double x104 = 4*(((x103 > 0) ? (
   0
)
: ((x103 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x105 = (1.0/5.0)*x49;
  const double x106 = 0.85599999999999998*x36;
  const double x107 = 0.20543999999999998*x15*x28;
  const double x108 = x22*x52*(((x23*x24*x49 - 9.9999999999999995e-21 < 0) ? (
   0
)
: ((x23*x24*x49 - 9.9999999999999995e-21 == 0) ? (
   1.0/2.0
)
: (
   1
))))/std::pow(x50, 2);
  const double x109 = 4*(((x103 < 0) ? (
   0
)
: ((x103 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x110 = 0.11036*x30*std::pow(x53, 3)*x68*(1 - std::pow(x54, 2));
  const double x111 = x18*x9;
  const double x112 = x111*x15;
  const double x113 = x3*x8;
  const double x114 = x113*x79;
  const double x115 = x61*x79;
  const double x116 = x111*x85;
  const double x117 = x116*x22;
  const double x118 = x116*x32;
  const double x119 = x111*x94;
  const double x120 = x1*x12;
  const double x121 = std::pow(y, -3);
  const double x122 = x23/x19;
  const double x123 = -1.0/20.0*x121*x25 + (1.0/16.0)*x122*x22;
  const double x124 = x26*x31;
  const double x125 = x122*x32;
  const double x126 = x93*((3.0/200.0)*x10 + 1.0/20.0)/x28;
  const double x127 = 0.010272*x43;
  const double x128 = 0.25679999999999997*x42;
  return (1.0/10.0)*x1*x11*x7 + (2.0/5.0)*x10*x43*(x70*x71 + 1.0/20000.0) - x11*(-x110*(x104*(x100*x123 + x102*(-11.111111111111111*x124 + 27.777777777777779*x125 + x126*x34)) + x109*(-x108*((5.0/2.0)*x122*x49 + x25*(x127*x40 + x127*x47 - x128*x41 - x128*x48)) - 6.8479999999999999*x121*x30*x51 + 0.34240000000000004*x22*x29*x51)) + 0.031*x29*x70 + x98*(-x76*(-0.15500000000000003*x10 - 0.77500000000000002) - x78*(x84*(x115*x120 + x120*x80) + x97*(2*x123*x90 + x96*(-22.222222222222221*x124 + 55.555555555555557*x125 + x126*x63))))) - 1.0/5.0*x112*(-x110*(x104*(-x101*x117 + x102*(-2.2222222222222223*x118 + 1.6666666666666665*x119)) + x109*(-x108*(-x105*x116 + x25*(-x106*x111 - x107*x114*x45 + 0.051359999999999996*M_PI*x11*x3*x9 + 0.20543999999999998*x15*x28*x3*x39*x79*x8)) + 1.0271999999999999*M_PI*x22*x28*x3*x51*x9)) + x111*x28*x73 + x98*(-x112*x77 - x78*(x84*(x113*x115 + x114*x83) + x97*(-x117*x91 + x96*(-4.4444444444444446*x118 + 3.333333333333333*x119))))) + x13*x14*x16 + x16*x17*x18 + x19*x21*(0.082799999999999999 - 0.0078000000000000014*x54) - x25*(1.712 - 1.712*x54)*(x37 + x41*x56 + x48*x56) - 1.0/5.0*x74*(-x110*(x104*(-x101*x87 + x102*(-2.2222222222222223*x92 + 1.6666666666666665*x95)) + x109*(-x108*(-x105*x86 + x25*(-x106*x72 - x107*x38*x82 + 0.051359999999999996*M_PI*x11*x5*x8 + 0.20543999999999998*x15*x28*x46*x5*x79*x9)) + 1.0271999999999999*M_PI*x22*x28*x5*x51*x8)) + x28*x72*x73 + x98*(-x74*x77 - x78*(x84*(x80*x81 + x82*x83) + x97*(-x87*x91 + x96*(-4.4444444444444446*x92 + 3.333333333333333*x95))))) - 1.0*(0.11281200000000008*x54 + 0.44035466666666673)*(std::pow(x12, 2)*x55*std::pow(x7, 2) + std::pow(x13, 2)*x39*x55 + std::pow(x17, 2)*x46*x55 + 1.0e-300);
}
inline double srcu0_A_1994(double x, double y, double z) {
  const double x0 = M_PI*y;
  const double x1 = std::cos(x0);
  const double x2 = M_PI*z;
  const double x3 = std::cos(x2);
  const double x4 = M_PI*x;
  const double x5 = std::sin(x4);
  const double x6 = (1.0/100.0)*M_PI;
  const double x7 = x5*x6;
  const double x8 = std::pow(std::sin(x0), 2);
  const double x9 = std::cos(x4);
  const double x10 = -x3;
  const double x11 = std::sin(x2);
  const double x12 = std::pow(x11, 2);
  const double x13 = x1 + x10;
  const double x14 = x5*x9;
  const double x15 = std::pow(M_PI, 2);
  const double x16 = 15.0/2.0 - 5.0/2.0*y;
  const double x17 = x11*x5;
  const double x18 = (1.0/5.0)*x17 + 1;
  const double x19 = 0.31*x16*x18;
  const double x20 = (1.0/25.0)*x8;
  const double x21 = x15*std::pow(x5, 2);
  const double x22 = (1.0/25.0)*x12;
  const double x23 = std::sqrt(x12*x15*x20 + x20*x21 + x21*x22 + 1.0e-300);
  const double x24 = std::pow(y, -2);
  const double x25 = 1.0/x16;
  const double x26 = x25/x18;
  const double x27 = (1.0/40.0)*x24*x26;
  const double x28 = (1.0/10.0)*y + 1.0/20.0;
  const double x29 = (3.0/10.0)*x17 + 1;
  const double x30 = x28*x29;
  const double x31 = std::sqrt(x30)/y;
  const double x32 = x26*x31;
  const double x33 = 22.222222222222221*x32;
  const double x34 = std::max(x27, x33);
  const double x35 = std::tanh(std::pow(x34, 2));
  const double x36 = std::max(x19, x23*x35);
  const double x37 = 1.0/x36;
  const double x38 = 0.31*x30;
  const double x39 = (1.0/5.0)*x13;
  const double x40 = M_PI*x9;
  const double x41 = x11*x40;
  const double x42 = x19 - x23*x35;
  const double x43 = std::pow(M_PI, 3)*x14;
  const double x44 = -x27 + x33;
  const double x45 = x25*x41/std::pow(x18, 2);
  return -x1*x3*x7 + x12*x7*(-x1 + x9) + std::pow(x13, 2)*x14*x6 + x15*x39*x5*(x37*x38 + 1.0/20000.0) - x39*x40*(0.092999999999999999*x28*x37*x41 + x38*(-0.062*x16*x41*(((x42 < 0) ? (
   0
)
: ((x42 == 0) ? (
   1.0/2.0
)
: (
   1
)))) - (x23*x34*(1 - std::pow(x35, 2))*(-1.0/100.0*x24*x45*(((x44 > 0) ? (
   0
)
: ((x44 == 0) ? (
   1.0/2.0
)
: (
   1
)))) + 2*(-4.4444444444444446*x31*x45 + 3.333333333333333*x32*x41/x29)*(((x44 < 0) ? (
   0
)
: ((x44 == 0) ? (
   1.0/2.0
)
: (
   1
))))) + x35*(x20*x43 + x22*x43)/x23)*(((x42 > 0) ? (
   0
)
: ((x42 == 0) ? (
   1.0/2.0
)
: (
   1
)))))/std::pow(x36, 2)) - x7*x8*(-x10 - x9);
}
inline double srcu1_A_1994(double x, double y, double z) {
  const double x0 = M_PI*x;
  const double x1 = std::cos(x0);
  const double x2 = M_PI*z;
  const double x3 = std::cos(x2);
  const double x4 = M_PI*y;
  const double x5 = std::sin(x4);
  const double x6 = (1.0/100.0)*M_PI;
  const double x7 = x5*x6;
  const double x8 = -x3;
  const double x9 = -x1 - x8;
  const double x10 = std::cos(x4);
  const double x11 = x10*x5;
  const double x12 = std::sin(x2);
  const double x13 = std::pow(x12, 2);
  const double x14 = std::sin(x0);
  const double x15 = std::pow(x14, 2);
  const double x16 = std::pow(M_PI, 2);
  const double x17 = 15.0/2.0 - 5.0/2.0*y;
  const double x18 = x12*x14;
  const double x19 = (1.0/5.0)*x18 + 1;
  const double x20 = 0.31*x17*x19;
  const double x21 = std::pow(x5, 2);
  const double x22 = (1.0/25.0)*x15;
  const double x23 = x16*x22;
  const double x24 = (1.0/25.0)*x13;
  const double x25 = std::sqrt(x13*x23 + x16*x21*x24 + x21*x23 + 1.0e-300);
  const double x26 = std::pow(y, -2);
  const double x27 = 1.0/x19;
  const double x28 = 1.0/x17;
  const double x29 = x27*x28;
  const double x30 = x26*x29;
  const double x31 = (1.0/10.0)*y + 1.0/20.0;
  const double x32 = (3.0/10.0)*x18 + 1;
  const double x33 = x31*x32;
  const double x34 = std::sqrt(x33);
  const double x35 = x34/y;
  const double x36 = 22.222222222222221*x29*x35;
  const double x37 = std::max(x36, (1.0/40.0)*x30);
  const double x38 = std::tanh(std::pow(x37, 2));
  const double x39 = x25*x38;
  const double x40 = std::max(x20, x39);
  const double x41 = 1.0/x40;
  const double x42 = 0.31*x33;
  const double x43 = (1.0/5.0)*x9;
  const double x44 = x20 - x39;
  const double x45 = std::pow(M_PI, 3)*x11;
  const double x46 = x27/std::pow(x17, 2);
  const double x47 = -1.0/40.0*x26*x27*x28 + x36;
  return -x1*x3*x7 - M_PI*x10*x43*(0.031*x32*x41 + x42*(-(-0.15500000000000003*x18 - 0.77500000000000002)*(((x44 < 0) ? (
   0
)
: ((x44 == 0) ? (
   1.0/2.0
)
: (
   1
)))) - (x25*x37*(1 - std::pow(x38, 2))*(2*((1.0/16.0)*x26*x46 - 1.0/20.0*x29/std::pow(y, 3))*(((x47 > 0) ? (
   0
)
: ((x47 == 0) ? (
   1.0/2.0
)
: (
   1
)))) + 2*(-22.222222222222221*x30*x34 + 55.555555555555557*x35*x46 + x36*((3.0/200.0)*x18 + 1.0/20.0)/(x31*x32))*(((x47 < 0) ? (
   0
)
: ((x47 == 0) ? (
   1.0/2.0
)
: (
   1
))))) + x38*(x22*x45 + x24*x45)/x25)*(((x44 > 0) ? (
   0
)
: ((x44 == 0) ? (
   1.0/2.0
)
: (
   1
)))))/std::pow(x40, 2)) + x11*x6*std::pow(x9, 2) - x13*x7*(x1 - x10) + x15*x7*(x10 + x8) + x16*x43*x5*(x41*x42 + 1.0/20000.0);
}
inline double srcu2_A_1994(double x, double y, double z) {
  const double x0 = M_PI*x;
  const double x1 = std::cos(x0);
  const double x2 = M_PI*y;
  const double x3 = std::cos(x2);
  const double x4 = M_PI*z;
  const double x5 = std::sin(x4);
  const double x6 = (1.0/100.0)*M_PI;
  const double x7 = x5*x6;
  const double x8 = std::pow(std::sin(x2), 2);
  const double x9 = std::cos(x4);
  const double x10 = -x9;
  const double x11 = x1 - x3;
  const double x12 = x5*x9;
  const double x13 = std::sin(x0);
  const double x14 = std::pow(x13, 2);
  const double x15 = std::pow(M_PI, 2);
  const double x16 = 15.0/2.0 - 5.0/2.0*y;
  const double x17 = x13*x5;
  const double x18 = (1.0/5.0)*x17 + 1;
  const double x19 = 0.31*x16*x18;
  const double x20 = (1.0/25.0)*x14;
  const double x21 = x15*x20;
  const double x22 = std::pow(x5, 2);
  const double x23 = (1.0/25.0)*x8;
  const double x24 = std::sqrt(x15*x22*x23 + x21*x22 + x21*x8 + 1.0e-300);
  const double x25 = std::pow(y, -2);
  const double x26 = 1.0/x16;
  const double x27 = x26/x18;
  const double x28 = (1.0/40.0)*x25*x27;
  const double x29 = (1.0/10.0)*y + 1.0/20.0;
  const double x30 = (3.0/10.0)*x17 + 1;
  const double x31 = x29*x30;
  const double x32 = std::sqrt(x31)/y;
  const double x33 = x27*x32;
  const double x34 = 22.222222222222221*x33;
  const double x35 = std::max(x28, x34);
  const double x36 = std::tanh(std::pow(x35, 2));
  const double x37 = std::max(x19, x24*x36);
  const double x38 = 1.0/x37;
  const double x39 = 0.31*x31;
  const double x40 = (1.0/5.0)*x11;
  const double x41 = M_PI*x9;
  const double x42 = x13*x41;
  const double x43 = x19 - x24*x36;
  const double x44 = std::pow(M_PI, 3)*x12;
  const double x45 = -x28 + x34;
  const double x46 = x26*x42/std::pow(x18, 2);
  return -x1*x3*x7 + std::pow(x11, 2)*x12*x6 - x14*x7*(x10 + x3) + x15*x40*x5*(x38*x39 + 1.0/20000.0) - x40*x41*(0.092999999999999999*x29*x38*x42 + x39*(-0.062*x16*x42*(((x43 < 0) ? (
   0
)
: ((x43 == 0) ? (
   1.0/2.0
)
: (
   1
)))) - (x24*x35*(1 - std::pow(x36, 2))*(-1.0/100.0*x25*x46*(((x45 > 0) ? (
   0
)
: ((x45 == 0) ? (
   1.0/2.0
)
: (
   1
)))) + 2*(-4.4444444444444446*x32*x46 + 3.333333333333333*x33*x42/x30)*(((x45 < 0) ? (
   0
)
: ((x45 == 0) ? (
   1.0/2.0
)
: (
   1
))))) + x36*(x20*x44 + x23*x44)/x24)*(((x43 > 0) ? (
   0
)
: ((x43 == 0) ? (
   1.0/2.0
)
: (
   1
)))))/std::pow(x37, 2)) + x7*x8*(-x1 - x10);
}
inline constexpr double nu_A = 5e-05;

inline double k_B(double x, double y, double z) {
  return (1.0/2.0 - 3.0/20.0*y)*((3.0/10.0)*std::sin(M_PI*x)*std::sin(M_PI*z) + 1);
}
inline double w_B(double x, double y, double z) {
  return ((6.0/25.0)*y + 6.0/25.0)*((1.0/5.0)*std::sin(M_PI*x)*std::sin(M_PI*z) + 1);
}
inline double p_B(double x, double y, double z) {
  return 0;
}
inline double u0_B(double x, double y, double z) {
  return (3.0/10.0)*y + (3.0/200.0)*(std::cos(M_PI*y) - std::cos(M_PI*z))*std::sin(M_PI*x) + 3.0/20.0;
}
inline double a0_B(double x, double y, double z) {
  return (3.0/200.0)*std::sin(M_PI*y)*std::sin(M_PI*z)/M_PI;
}
inline double u1_B(double x, double y, double z) {
  return (3.0/200.0)*(-std::cos(M_PI*x) + std::cos(M_PI*z))*std::sin(M_PI*y);
}
inline double a1_B(double x, double y, double z) {
  return (3.0/200.0)*std::sin(M_PI*x)*std::sin(M_PI*z)/M_PI;
}
inline double u2_B(double x, double y, double z) {
  return (3.0/200.0)*(std::cos(M_PI*x) - std::cos(M_PI*y))*std::sin(M_PI*z);
}
inline double a2_B(double x, double y, double z) {
  return (3.0/20.0)*std::pow(y, 2) + (3.0/20.0)*y + (3.0/200.0)*std::sin(M_PI*x)*std::sin(M_PI*y)/M_PI;
}
inline double srck_B_2003(double x, double y, double z) {
  const double x0 = M_PI*y;
  const double x1 = std::sin(x0);
  const double x2 = M_PI*x;
  const double x3 = std::cos(x2);
  const double x4 = M_PI*z;
  const double x5 = std::cos(x4);
  const double x6 = -x5;
  const double x7 = -x3 - x6;
  const double x8 = std::sin(x2);
  const double x9 = std::sin(x4);
  const double x10 = x8*x9;
  const double x11 = -9.0/200.0*x10 - 3.0/20.0;
  const double x12 = 1.0/2.0 - 3.0/20.0*y;
  const double x13 = std::cos(x0);
  const double x14 = -x13 + x3;
  const double x15 = M_PI*x5;
  const double x16 = (3.0/10.0)*x10 + 1;
  const double x17 = x12*x16;
  const double x18 = (1.0/5.0)*x10 + 1;
  const double x19 = (6.0/25.0)*y + 6.0/25.0;
  const double x20 = x18*x19;
  const double x21 = x17*x20;
  const double x22 = x13 + x6;
  const double x23 = M_PI*x3*x9;
  const double x24 = (3.0/10.0)*x12;
  const double x25 = x23*x24;
  const double x26 = 0.31*x20;
  const double x27 = std::pow(x7, 2);
  const double x28 = std::pow(x13, 2);
  const double x29 = std::pow(M_PI, 2);
  const double x30 = (9.0/20000.0)*x29;
  const double x31 = std::pow(x14, 2);
  const double x32 = std::pow(x5, 2);
  const double x33 = std::pow(x22, 2);
  const double x34 = std::pow(x3, 2);
  const double x35 = x27*x28*x30 + x30*x31*x32 + x30*x33*x34 + 0.089999999999999997;
  const double x36 = std::sqrt(x35);
  const double x37 = std::pow(y, -2);
  const double x38 = 1.0/x18;
  const double x39 = 1.0/x19;
  const double x40 = x38*x39;
  const double x41 = x37*x40;
  const double x42 = (1.0/40.0)*x41;
  const double x43 = std::sqrt(x17);
  const double x44 = 22.222222222222221*x43;
  const double x45 = 1.0/y;
  const double x46 = x40*x45;
  const double x47 = x44*x46;
  const double x48 = std::max(x42, x47);
  const double x49 = std::tanh(std::pow(x48, 2));
  const double x50 = x36*x49;
  const double x51 = std::max(x26, x50);
  const double x52 = 1.0/x51;
  const double x53 = 0.31*x17;
  const double x54 = 11.111111111111111*x43;
  const double x55 = x46*x54;
  const double x56 = std::max(x42, x55);
  const double x57 = (6.0/125.0)*x10 + 6.0/25.0;
  const double x58 = std::pow(x8, 2);
  const double x59 = x32*x58;
  const double x60 = x19*x59;
  const double x61 = x12*x29;
  const double x62 = 0.10271999999999999*x61;
  const double x63 = std::pow(x9, 2);
  const double x64 = x34*x63;
  const double x65 = x19*x64;
  const double x66 = 1.712*x11*x57 + x60*x62 + x62*x65;
  const double x67 = std::max(1.0e-10, x40*x66);
  const double x68 = 1.0/x67;
  const double x69 = x37*x68;
  const double x70 = 3.4239999999999999*x17;
  const double x71 = std::min(x56, x69*x70);
  const double x72 = std::tanh(std::pow(x71, 4));
  const double x73 = 1.0 - 0.15000000000000002*x72;
  const double x74 = x52*x73;
  const double x75 = x15*x8;
  const double x76 = 0.092999999999999999*x74;
  const double x77 = x26 - x50;
  const double x78 = (((x77 < 0) ? (
   0
)
: ((x77 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x79 = 0.062*x19*x78;
  const double x80 = (((x77 > 0) ? (
   0
)
: ((x77 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x81 = std::pow(M_PI, 3);
  const double x82 = (9.0/20000.0)*x81;
  const double x83 = x82*x9;
  const double x84 = x49/x36;
  const double x85 = x39/std::pow(x18, 2);
  const double x86 = x75*x85;
  const double x87 = x37*x86;
  const double x88 = -1.0/40.0*x37*x38*x39;
  const double x89 = x47 + x88;
  const double x90 = (((x89 > 0) ? (
   0
)
: ((x89 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x91 = (1.0/100.0)*x90;
  const double x92 = x43*x45;
  const double x93 = x86*x92;
  const double x94 = 1.0/x16;
  const double x95 = x43*x46*x94;
  const double x96 = x75*x95;
  const double x97 = 2*(((x89 < 0) ? (
   0
)
: ((x89 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x98 = x36*x48*(1 - std::pow(x49, 2));
  const double x99 = std::pow(x51, -2);
  const double x100 = x53*x73*x99;
  const double x101 = x55 + x88;
  const double x102 = (((x101 > 0) ? (
   0
)
: ((x101 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x103 = (1.0/200.0)*x102;
  const double x104 = (((x101 < 0) ? (
   0
)
: ((x101 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x105 = -3.4239999999999999*x12*x16*x37*x68 + x56;
  const double x106 = 4*(((x105 > 0) ? (
   0
)
: ((x105 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x107 = (1.0/5.0)*x66;
  const double x108 = 0.077039999999999997*x57;
  const double x109 = 0.20543999999999998*x12*x19*x81;
  const double x110 = x37*x70*(((x38*x39*x66 - 1.0e-10 < 0) ? (
   0
)
: ((x38*x39*x66 - 1.0e-10 == 0) ? (
   1.0/2.0
)
: (
   1
))))/std::pow(x67, 2);
  const double x111 = 4*(((x105 < 0) ? (
   0
)
: ((x105 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x112 = 0.046500000000000007*x17*x52*std::pow(x71, 3)*(1 - std::pow(x72, 2));
  const double x113 = x8*x82;
  const double x114 = x23*x85;
  const double x115 = x114*x37;
  const double x116 = x114*x92;
  const double x117 = x23*x95;
  const double x118 = x1*x82;
  const double x119 = std::pow(y, -3);
  const double x120 = x38/std::pow(x19, 2);
  const double x121 = -1.0/20.0*x119*x40 - 3.0/500.0*x120*x37;
  const double x122 = x120*x92;
  const double x123 = 1.0/x12;
  const double x124 = -9.0/400.0*x10 - 3.0/40.0;
  const double x125 = 0.024652799999999996*x61;
  const double x126 = 0.015407999999999998*x29;
  return (3.0/200.0)*x1*x11*x7 + (9.0/2000.0)*x10*x12*x14*x15 + (3.0/5.0)*x10*x61*(x53*x74 + 1.0/20000.0) - x11*(-x112*(x106*(x102*x121 + x104*(-2.6666666666666665*x122 + 11.111111111111111*x123*x124*x38*x39*x43*x45*x94 - x41*x54)) + x111*(-x110*(-6.0/25.0*x120*x66 + x40*(x125*x59 + x125*x64 - x126*x60 - x126*x65)) - 6.8479999999999999*x119*x17*x68 - 0.51359999999999995*x16*x69)) + 0.31*x12*x16*x73*x99*(-x78*(0.014879999999999999*x10 + 0.074399999999999994) - x80*(x84*((9.0/20000.0)*x1*x14*x32*x81 - x118*x13*x27 - x118*x22*x34) + x98*(2*x121*x90 + x97*(-5.333333333333333*x122 + 22.222222222222221*x123*x124*x38*x39*x43*x45*x94 - x41*x44)))) - 0.0465*x16*x74) + 0.089999999999999997*x21 - x24*x75*(x100*(-x75*x79 - x80*(x84*((9.0/20000.0)*x22*x34*x81*x9 - x28*x7*x83 - x31*x5*x83) + x98*(-x87*x91 + x97*(-4.4444444444444446*x93 + 3.333333333333333*x96)))) - x112*(x106*(-x103*x87 + x104*(-2.2222222222222223*x93 + 1.6666666666666665*x96)) + x111*(-x110*(-x107*x86 + x40*(-x108*x75 - x109*x5*x58*x9 + 0.082175999999999999*M_PI*x11*x5*x8 + 0.20543999999999998*x12*x19*x34*x5*x81*x9)) + 1.0271999999999999*M_PI*x12*x37*x5*x68*x8)) + x12*x75*x76) - x25*(x100*(-x23*x79 - x80*(x84*(-x113*x14*x32 - x113*x3*x33 + (9.0/20000.0)*x28*x7*x8*x81) + x98*(-x115*x91 + x97*(-4.4444444444444446*x116 + 3.333333333333333*x117)))) - x112*(x106*(-x103*x115 + x104*(-2.2222222222222223*x116 + 1.6666666666666665*x117)) + x111*(-x110*(-x107*x114 + x40*(-x108*x23 - x109*x3*x63*x8 + 0.082175999999999999*M_PI*x11*x3*x9 + 0.20543999999999998*x12*x19*x3*x32*x8*x81)) + 1.0271999999999999*M_PI*x12*x3*x37*x68*x9)) + x12*x23*x76) + x25*((3.0/200.0)*x22*x8 + (3.0/10.0)*y + 3.0/20.0) - std::min(0.89999999999999991*x21, x35*x52*x53);
}
inline double srcw_B_2003(double x, double y, double z) {
  const double x0 = M_PI*y;
  const double x1 = std::sin(x0);
  const double x2 = M_PI*x;
  const double x3 = std::cos(x2);
  const double x4 = M_PI*z;
  const double x5 = std::cos(x4);
  const double x6 = -x5;
  const double x7 = -x3 - x6;
  const double x8 = std::sin(x2);
  const double x9 = std::sin(x4);
  const double x10 = x8*x9;
  const double x11 = (6.0/125.0)*x10 + 6.0/25.0;
  const double x12 = std::cos(x0);
  const double x13 = -x12 + x3;
  const double x14 = M_PI*x5;
  const double x15 = (6.0/25.0)*y + 6.0/25.0;
  const double x16 = x10*x15;
  const double x17 = x12 + x6;
  const double x18 = M_PI*x3*x9;
  const double x19 = x15*x18;
  const double x20 = (1.0/5.0)*x19;
  const double x21 = std::pow(x15, 2);
  const double x22 = (1.0/5.0)*x10 + 1;
  const double x23 = std::pow(x22, 2);
  const double x24 = std::pow(y, -2);
  const double x25 = 1.0/x22;
  const double x26 = 1.0/x15;
  const double x27 = x25*x26;
  const double x28 = x24*x27;
  const double x29 = (1.0/40.0)*x28;
  const double x30 = 1.0/y;
  const double x31 = x27*x30;
  const double x32 = 1.0/2.0 - 3.0/20.0*y;
  const double x33 = (3.0/10.0)*x10 + 1;
  const double x34 = x32*x33;
  const double x35 = std::sqrt(x34);
  const double x36 = 11.111111111111111*x35;
  const double x37 = x31*x36;
  const double x38 = std::max(x29, x37);
  const double x39 = -9.0/200.0*x10 - 3.0/20.0;
  const double x40 = x11*x39;
  const double x41 = std::pow(x5, 2);
  const double x42 = std::pow(x8, 2);
  const double x43 = x41*x42;
  const double x44 = x15*x43;
  const double x45 = std::pow(M_PI, 2);
  const double x46 = x32*x45;
  const double x47 = 0.10271999999999999*x46;
  const double x48 = std::pow(x3, 2);
  const double x49 = std::pow(x9, 2);
  const double x50 = x48*x49;
  const double x51 = x15*x50;
  const double x52 = 1.712*x40 + x44*x47 + x47*x51;
  const double x53 = std::max(1.0e-10, x27*x52);
  const double x54 = 1.0/x53;
  const double x55 = x24*x54;
  const double x56 = 3.4239999999999999*x34;
  const double x57 = std::min(x38, x55*x56);
  const double x58 = std::tanh(std::pow(x57, 4));
  const double x59 = (3.0/50.0)*x46;
  const double x60 = x15*x22;
  const double x61 = 0.31*x60;
  const double x62 = std::pow(x7, 2);
  const double x63 = std::pow(x12, 2);
  const double x64 = (9.0/20000.0)*x45;
  const double x65 = std::pow(x13, 2);
  const double x66 = std::pow(x17, 2);
  const double x67 = x41*x64*x65 + x48*x64*x66 + x62*x63*x64 + 0.089999999999999997;
  const double x68 = std::sqrt(x67);
  const double x69 = 22.222222222222221*x35;
  const double x70 = x31*x69;
  const double x71 = std::max(x29, x70);
  const double x72 = std::tanh(std::pow(x71, 2));
  const double x73 = x68*x72;
  const double x74 = std::max(x61, x73);
  const double x75 = 1.0/x74;
  const double x76 = 0.85599999999999998 - 0.35599999999999998*x58;
  const double x77 = x75*x76;
  const double x78 = 0.31*x34;
  const double x79 = 1.0/x33;
  const double x80 = 1.0/x32;
  const double x81 = x14*x8;
  const double x82 = 0.092999999999999999*x77;
  const double x83 = x15*x81;
  const double x84 = x61 - x73;
  const double x85 = (((x84 < 0) ? (
   0
)
: ((x84 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x86 = 0.062*x85;
  const double x87 = (((x84 > 0) ? (
   0
)
: ((x84 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x88 = std::pow(M_PI, 3);
  const double x89 = (9.0/20000.0)*x88;
  const double x90 = x89*x9;
  const double x91 = x72/x68;
  const double x92 = x26/x23;
  const double x93 = x81*x92;
  const double x94 = x24*x93;
  const double x95 = -1.0/40.0*x24*x25*x26;
  const double x96 = x70 + x95;
  const double x97 = (((x96 > 0) ? (
   0
)
: ((x96 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x98 = (1.0/100.0)*x97;
  const double x99 = x30*x35;
  const double x100 = x93*x99;
  const double x101 = x31*x35*x79;
  const double x102 = x101*x81;
  const double x103 = 2*(((x96 < 0) ? (
   0
)
: ((x96 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x104 = x68*x71*(1 - std::pow(x72, 2));
  const double x105 = std::pow(x74, -2);
  const double x106 = x105*x76*x78;
  const double x107 = x37 + x95;
  const double x108 = (((x107 > 0) ? (
   0
)
: ((x107 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x109 = (1.0/200.0)*x108;
  const double x110 = (((x107 < 0) ? (
   0
)
: ((x107 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x111 = -3.4239999999999999*x24*x32*x33*x54 + x38;
  const double x112 = 4*(((x111 > 0) ? (
   0
)
: ((x111 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x113 = (1.0/5.0)*x52;
  const double x114 = 0.077039999999999997*x11;
  const double x115 = 0.20543999999999998*x15*x32*x88;
  const double x116 = x24*x56*(((x25*x26*x52 - 1.0e-10 < 0) ? (
   0
)
: ((x25*x26*x52 - 1.0e-10 == 0) ? (
   1.0/2.0
)
: (
   1
))))/std::pow(x53, 2);
  const double x117 = 4*(((x111 < 0) ? (
   0
)
: ((x111 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x118 = 0.11036*x34*std::pow(x57, 3)*x75*(1 - std::pow(x58, 2));
  const double x119 = x8*x89;
  const double x120 = x18*x92;
  const double x121 = x120*x24;
  const double x122 = x120*x99;
  const double x123 = x101*x18;
  const double x124 = x1*x89;
  const double x125 = std::pow(y, -3);
  const double x126 = x25/x21;
  const double x127 = -1.0/20.0*x125*x27 - 3.0/500.0*x126*x24;
  const double x128 = x126*x99;
  const double x129 = -9.0/400.0*x10 - 3.0/40.0;
  const double x130 = 0.024652799999999996*x46;
  const double x131 = 0.015407999999999998*x45;
  return (3.0/200.0)*x1*x11*x7 - x11*(0.31*x105*x32*x33*x76*(-x85*(0.014879999999999999*x10 + 0.074399999999999994) - x87*(x104*(x103*(-5.333333333333333*x128 + 22.222222222222221*x129*x25*x26*x30*x35*x79*x80 - x28*x69) + 2*x127*x97) + x91*((9.0/20000.0)*x1*x13*x41*x88 - x12*x124*x62 - x124*x17*x48))) - x118*(x112*(x108*x127 + x110*(-2.6666666666666665*x128 + 11.111111111111111*x129*x25*x26*x30*x35*x79*x80 - x28*x36)) + x117*(-x116*(-6.0/25.0*x126*x52 + x27*(x130*x43 + x130*x50 - x131*x44 - x131*x51)) - 6.8479999999999999*x125*x34*x54 - 0.51359999999999995*x33*x55)) - 0.0465*x33*x77) + (3.0/1000.0)*x13*x14*x16 + (2.0/5.0)*x16*x45*(x77*x78 + 1.0/20000.0) - x20*(x106*(-x19*x86 - x87*(x104*(x103*(-4.4444444444444446*x122 + 3.333333333333333*x123) - x121*x98) + x91*(-x119*x13*x41 - x119*x3*x66 + (9.0/20000.0)*x63*x7*x8*x88))) - x118*(x112*(-x109*x121 + x110*(-2.2222222222222223*x122 + 1.6666666666666665*x123)) + x117*(-x116*(-x113*x120 + x27*(-x114*x18 - x115*x3*x49*x8 + 0.20543999999999998*x15*x3*x32*x41*x8*x88 + 0.082175999999999999*M_PI*x3*x39*x9)) + 1.0271999999999999*M_PI*x24*x3*x32*x54*x9)) + x18*x32*x82) + x20*((3.0/200.0)*x17*x8 + (3.0/10.0)*y + 3.0/20.0) + x21*x23*(0.082799999999999999 - 0.0078000000000000014*x58) - x27*(1.712 - 1.712*x58)*(x40 + x44*x59 + x51*x59) - 3.2258064516129035*x74*x79*x80*(0.11555555555555558*x58 + 0.44)*std::min(0.89999999999999991*x34*x60, x67*x75*x78) - 1.0/5.0*x83*(x106*(-x83*x86 - x87*(x104*(x103*(-4.4444444444444446*x100 + 3.333333333333333*x102) - x94*x98) + x91*((9.0/20000.0)*x17*x48*x88*x9 - x5*x65*x90 - x63*x7*x90))) - x118*(x112*(-x109*x94 + x110*(-2.2222222222222223*x100 + 1.6666666666666665*x102)) + x117*(-x116*(-x113*x93 + x27*(-x114*x81 - x115*x42*x5*x9 + 0.20543999999999998*x15*x32*x48*x5*x88*x9 + 0.082175999999999999*M_PI*x39*x5*x8)) + 1.0271999999999999*M_PI*x24*x32*x5*x54*x8)) + x32*x81*x82);
}
inline double srcu0_B_2003(double x, double y, double z) {
  const double x0 = M_PI*x;
  const double x1 = std::sin(x0);
  const double x2 = M_PI*z;
  const double x3 = std::sin(x2);
  const double x4 = std::cos(x0);
  const double x5 = M_PI*y;
  const double x6 = std::cos(x5);
  const double x7 = x4 - x6;
  const double x8 = std::sin(x5);
  const double x9 = std::cos(x2);
  const double x10 = -x9;
  const double x11 = -x10 - x4;
  const double x12 = (3.0/200.0)*x1;
  const double x13 = x10 + x6;
  const double x14 = M_PI*x4;
  const double x15 = x1*x3;
  const double x16 = (3.0/10.0)*x15 + 1;
  const double x17 = (6.0/25.0)*y + 6.0/25.0;
  const double x18 = (1.0/5.0)*x15 + 1;
  const double x19 = 0.31*x17*x18;
  const double x20 = std::pow(x11, 2);
  const double x21 = std::pow(x6, 2);
  const double x22 = std::pow(M_PI, 2);
  const double x23 = (9.0/20000.0)*x22;
  const double x24 = std::pow(x9, 2);
  const double x25 = std::pow(x13, 2);
  const double x26 = std::pow(x4, 2);
  const double x27 = std::sqrt(x20*x21*x23 + x23*x24*std::pow(x7, 2) + x23*x25*x26 + 0.089999999999999997);
  const double x28 = 1.0/x17;
  const double x29 = std::pow(y, -2);
  const double x30 = 1.0/x18;
  const double x31 = x29*x30;
  const double x32 = x28*x31;
  const double x33 = (1.0/40.0)*x32;
  const double x34 = 1.0/2.0 - 3.0/20.0*y;
  const double x35 = x16*x34;
  const double x36 = std::sqrt(x35);
  const double x37 = 22.222222222222221*x36;
  const double x38 = 1.0/y;
  const double x39 = x28*x30;
  const double x40 = x38*x39;
  const double x41 = x37*x40;
  const double x42 = std::max(x33, x41);
  const double x43 = std::tanh(std::pow(x42, 2));
  const double x44 = std::max(x19, x27*x43);
  const double x45 = 1.0/x44;
  const double x46 = 0.31*x35;
  const double x47 = (3.0/100.0)*x13;
  const double x48 = std::pow(x44, -2);
  const double x49 = x19 - x27*x43;
  const double x50 = (((x49 < 0) ? (
   0
)
: ((x49 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x51 = (((x49 > 0) ? (
   0
)
: ((x49 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x52 = std::pow(M_PI, 3);
  const double x53 = (9.0/20000.0)*x52;
  const double x54 = x53*x8;
  const double x55 = x43/x27;
  const double x56 = std::pow(x17, -2);
  const double x57 = -x33 + x41;
  const double x58 = (((x57 > 0) ? (
   0
)
: ((x57 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x59 = x36*x38;
  const double x60 = 1.0/x16;
  const double x61 = 2*(((x57 < 0) ? (
   0
)
: ((x57 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x62 = x27*x42*(1 - std::pow(x43, 2));
  const double x63 = x14*x3;
  const double x64 = x1*x53;
  const double x65 = x28*x63/std::pow(x18, 2);
  return x1*x22*x47*(x45*x46 + 1.0/20000.0) + (9.0/40000.0)*M_PI*x1*std::pow(x3, 2)*x7 + (3.0/200.0)*x11*x8*(-M_PI*x12*x8 + 3.0/10.0) + (3.0/200.0)*x13*x14*(x12*x13 + (3.0/10.0)*y + 3.0/20.0) - x14*x47*(0.092999999999999999*x34*x45*x63 + x46*x48*(-0.062*x17*x50*x63 - x51*(x55*((9.0/20000.0)*x1*x11*x21*x52 - x24*x64*x7 - x25*x4*x64) + x62*(-1.0/100.0*x29*x58*x65 + x61*(3.333333333333333*x36*x40*x60*x63 - 4.4444444444444446*x59*x65))))) + 0.013949999999999999*x16*x45 - 0.092999999999999999*x35*x48*(-x50*(0.014879999999999999*x15 + 0.074399999999999994) - x51*(x55*(-x13*x26*x54 - x20*x54*x6 + (9.0/20000.0)*x24*x52*x7*x8) + x62*(2*x58*(-3.0/500.0*x31*x56 - 1.0/20.0*x39/std::pow(y, 3)) + x61*(22.222222222222221*x28*x30*x36*x38*x60*(-9.0/400.0*x15 - 3.0/40.0)/x34 - 5.333333333333333*x30*x56*x59 - x32*x37))));
}
inline double srcu1_B_2003(double x, double y, double z) {
  const double x0 = M_PI*y;
  const double x1 = std::sin(x0);
  const double x2 = std::cos(x0);
  const double x3 = M_PI*x;
  const double x4 = std::cos(x3);
  const double x5 = M_PI*z;
  const double x6 = std::cos(x5);
  const double x7 = -x6;
  const double x8 = -x4 - x7;
  const double x9 = std::pow(x8, 2);
  const double x10 = std::sin(x5);
  const double x11 = -x2 + x4;
  const double x12 = std::sin(x3);
  const double x13 = x2 + x7;
  const double x14 = 1.0/2.0 - 3.0/20.0*y;
  const double x15 = (6.0/25.0)*y + 6.0/25.0;
  const double x16 = x10*x12;
  const double x17 = (1.0/5.0)*x16 + 1;
  const double x18 = 0.31*x15*x17;
  const double x19 = std::pow(x2, 2);
  const double x20 = std::pow(M_PI, 2);
  const double x21 = (9.0/20000.0)*x20;
  const double x22 = std::pow(x6, 2);
  const double x23 = std::pow(x13, 2);
  const double x24 = std::pow(x4, 2);
  const double x25 = std::sqrt(std::pow(x11, 2)*x21*x22 + x19*x21*x9 + x21*x23*x24 + 0.089999999999999997);
  const double x26 = 1.0/x15;
  const double x27 = std::pow(y, -2);
  const double x28 = 1.0/x17;
  const double x29 = x27*x28;
  const double x30 = x26*x29;
  const double x31 = (3.0/10.0)*x16 + 1;
  const double x32 = x14*x31;
  const double x33 = std::sqrt(x32);
  const double x34 = 22.222222222222221*x33;
  const double x35 = 1.0/y;
  const double x36 = x26*x28;
  const double x37 = x35*x36;
  const double x38 = x34*x37;
  const double x39 = std::max(x38, (1.0/40.0)*x30);
  const double x40 = std::tanh(std::pow(x39, 2));
  const double x41 = x25*x40;
  const double x42 = std::max(x18, x41);
  const double x43 = 1.0/x42;
  const double x44 = M_PI*x10*x4;
  const double x45 = 0.31*x32;
  const double x46 = std::pow(x42, -2);
  const double x47 = x18 - x41;
  const double x48 = (((x47 < 0) ? (
   0
)
: ((x47 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x49 = (((x47 > 0) ? (
   0
)
: ((x47 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x50 = std::pow(M_PI, 3);
  const double x51 = (9.0/20000.0)*x50;
  const double x52 = x40/x25;
  const double x53 = -1.0/40.0*x26*x27*x28 + x38;
  const double x54 = (((x53 > 0) ? (
   0
)
: ((x53 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x55 = x26*x44/std::pow(x17, 2);
  const double x56 = x33*x35;
  const double x57 = 1.0/x31;
  const double x58 = 2*(((x53 < 0) ? (
   0
)
: ((x53 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x59 = x25*x39*(1 - std::pow(x40, 2));
  const double x60 = x1*x51;
  const double x61 = std::pow(x15, -2);
  return -9.0/40000.0*M_PI*x1*std::pow(x10, 2)*x11 + (3.0/200.0)*M_PI*x1*x12*((3.0/200.0)*x12*x13 + (3.0/10.0)*y + 3.0/20.0) + (9.0/40000.0)*M_PI*x1*x2*x9 + (3.0/100.0)*x1*x20*x8*(x43*x45 + 1.0/20000.0) - 0.027899999999999998*x14*x43*x44 - 3.0/100.0*M_PI*x2*x8*(-0.0465*x31*x43 + x45*x46*(-x48*(0.014879999999999999*x16 + 0.074399999999999994) - x49*(x52*((9.0/20000.0)*x1*x11*x22*x50 - x13*x24*x60 - x2*x60*x9) + x59*(2*x54*(-3.0/500.0*x29*x61 - 1.0/20.0*x36/std::pow(y, 3)) + x58*(-5.333333333333333*x28*x56*x61 - x30*x34 + 22.222222222222221*x26*x28*x33*x35*x57*(-9.0/400.0*x16 - 3.0/40.0)/x14))))) - 0.092999999999999999*x32*x46*(-0.062*x15*x44*x48 - x49*(x52*(-x11*x12*x22*x51 + (9.0/20000.0)*x12*x19*x50*x8 - x12*x23*x4*x51) + x59*(-1.0/100.0*x27*x54*x55 + x58*(3.333333333333333*x33*x37*x44*x57 - 4.4444444444444446*x55*x56))));
}
inline double srcu2_B_2003(double x, double y, double z) {
  const double x0 = M_PI*x;
  const double x1 = std::cos(x0);
  const double x2 = M_PI*z;
  const double x3 = std::cos(x2);
  const double x4 = -x3;
  const double x5 = -x1 - x4;
  const double x6 = M_PI*y;
  const double x7 = std::sin(x2);
  const double x8 = (9.0/40000.0)*M_PI*x7;
  const double x9 = std::cos(x6);
  const double x10 = x1 - x9;
  const double x11 = std::pow(x10, 2);
  const double x12 = x11*x3;
  const double x13 = std::sin(x0);
  const double x14 = x4 + x9;
  const double x15 = x13*x7;
  const double x16 = std::pow(M_PI, 2);
  const double x17 = (6.0/25.0)*y + 6.0/25.0;
  const double x18 = (1.0/5.0)*x15 + 1;
  const double x19 = 0.31*x17*x18;
  const double x20 = std::pow(x9, 2);
  const double x21 = (9.0/20000.0)*x16;
  const double x22 = std::pow(x1, 2);
  const double x23 = std::sqrt(x11*x21*std::pow(x3, 2) + std::pow(x14, 2)*x21*x22 + x20*x21*std::pow(x5, 2) + 0.089999999999999997);
  const double x24 = std::pow(y, -2);
  const double x25 = 1.0/x17;
  const double x26 = x25/x18;
  const double x27 = (1.0/40.0)*x24*x26;
  const double x28 = 1.0/2.0 - 3.0/20.0*y;
  const double x29 = (3.0/10.0)*x15 + 1;
  const double x30 = x28*x29;
  const double x31 = std::sqrt(x30)/y;
  const double x32 = x26*x31;
  const double x33 = 22.222222222222221*x32;
  const double x34 = std::max(x27, x33);
  const double x35 = std::tanh(std::pow(x34, 2));
  const double x36 = std::max(x19, x23*x35);
  const double x37 = 1.0/x36;
  const double x38 = 0.31*x30;
  const double x39 = (3.0/100.0)*x10;
  const double x40 = M_PI*x3;
  const double x41 = x13*x40;
  const double x42 = x19 - x23*x35;
  const double x43 = std::pow(M_PI, 3);
  const double x44 = (9.0/20000.0)*x43*x7;
  const double x45 = -x27 + x33;
  const double x46 = x25*x41/std::pow(x18, 2);
  return x12*x8 - 3.0/200.0*M_PI*x15*((3.0/200.0)*x13*x14 + (3.0/10.0)*y + 3.0/20.0) + x16*x39*x7*(x37*x38 + 1.0/20000.0) - x39*x40*(0.092999999999999999*x28*x37*x41 + x38*(-0.062*x17*x41*(((x42 < 0) ? (
   0
)
: ((x42 == 0) ? (
   1.0/2.0
)
: (
   1
)))) - (x23*x34*(1 - std::pow(x35, 2))*(-1.0/100.0*x24*x46*(((x45 > 0) ? (
   0
)
: ((x45 == 0) ? (
   1.0/2.0
)
: (
   1
)))) + 2*(-4.4444444444444446*x31*x46 + 3.333333333333333*x32*x41/x29)*(((x45 < 0) ? (
   0
)
: ((x45 == 0) ? (
   1.0/2.0
)
: (
   1
))))) + x35*(-x12*x44 + (9.0/20000.0)*x14*x22*x43*x7 - x20*x44*x5)/x23)*(((x42 > 0) ? (
   0
)
: ((x42 == 0) ? (
   1.0/2.0
)
: (
   1
)))))/std::pow(x36, 2)) + x5*x8*std::pow(std::sin(x6), 2);
}
inline double srck_B_1994(double x, double y, double z) {
  const double x0 = M_PI*x;
  const double x1 = std::sin(x0);
  const double x2 = M_PI*z;
  const double x3 = std::sin(x2);
  const double x4 = x1*x3;
  const double x5 = -9.0/200.0*x4 - 3.0/20.0;
  const double x6 = std::cos(x0);
  const double x7 = std::cos(x2);
  const double x8 = -x7;
  const double x9 = -x6 - x8;
  const double x10 = M_PI*y;
  const double x11 = std::sin(x10);
  const double x12 = (3.0/200.0)*x11;
  const double x13 = std::cos(x10);
  const double x14 = -x13 + x6;
  const double x15 = 1.0/2.0 - 3.0/20.0*y;
  const double x16 = x15*x4;
  const double x17 = (3.0/10.0)*x4 + 1;
  const double x18 = x15*x17;
  const double x19 = (1.0/5.0)*x4 + 1;
  const double x20 = (6.0/25.0)*y + 6.0/25.0;
  const double x21 = x19*x20;
  const double x22 = x18*x21;
  const double x23 = x13 + x8;
  const double x24 = (3.0/200.0)*x1;
  const double x25 = M_PI*x3*x6;
  const double x26 = (3.0/10.0)*x15;
  const double x27 = x25*x26;
  const double x28 = 0.31*x21;
  const double x29 = std::pow(x3, 2);
  const double x30 = (9.0/10000.0)*x29;
  const double x31 = std::pow(M_PI, 2);
  const double x32 = std::pow(x1, 2);
  const double x33 = x31*x32;
  const double x34 = std::pow(x11, 2);
  const double x35 = M_PI*x1;
  const double x36 = (3.0/100.0)*x11*x35 - 3.0/10.0;
  const double x37 = -x36;
  const double x38 = std::sqrt(x30*x31*x34 + x30*x33 + (1.0/2.0)*std::pow(x36, 2) + (1.0/2.0)*std::pow(x37, 2) + 1.0e-300);
  const double x39 = std::pow(y, -2);
  const double x40 = 1.0/x19;
  const double x41 = 1.0/x20;
  const double x42 = x40*x41;
  const double x43 = x39*x42;
  const double x44 = (1.0/40.0)*x43;
  const double x45 = std::sqrt(x18);
  const double x46 = 22.222222222222221*x45;
  const double x47 = 1.0/y;
  const double x48 = x42*x47;
  const double x49 = x46*x48;
  const double x50 = std::max(x44, x49);
  const double x51 = std::tanh(std::pow(x50, 2));
  const double x52 = x38*x51;
  const double x53 = std::max(x28, x52);
  const double x54 = 1.0/x53;
  const double x55 = (9.0/20000.0)*x31;
  const double x56 = std::pow(x7, 2);
  const double x57 = std::pow(x6, 2);
  const double x58 = 0.31*x18;
  const double x59 = 11.111111111111111*x45;
  const double x60 = x48*x59;
  const double x61 = std::max(x44, x60);
  const double x62 = (6.0/125.0)*x4 + 6.0/25.0;
  const double x63 = x33*x56;
  const double x64 = x15*x20;
  const double x65 = 0.10271999999999999*x64;
  const double x66 = x29*x31*x57;
  const double x67 = 1.712*x5*x62 + x63*x65 + x65*x66;
  const double x68 = std::max(9.9999999999999995e-21, x42*x67);
  const double x69 = 1.0/x68;
  const double x70 = x39*x69;
  const double x71 = 3.4239999999999999*x18;
  const double x72 = std::min(x61, x70*x71);
  const double x73 = std::tanh(std::pow(x72, 4));
  const double x74 = 1.0 - 0.15000000000000002*x73;
  const double x75 = x54*x74;
  const double x76 = x35*x7;
  const double x77 = 0.092999999999999999*x75;
  const double x78 = x28 - x52;
  const double x79 = (((x78 < 0) ? (
   0
)
: ((x78 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x80 = 0.062*x20*x79;
  const double x81 = (((x78 > 0) ? (
   0
)
: ((x78 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x82 = std::pow(M_PI, 3);
  const double x83 = x3*x7*x82;
  const double x84 = (9.0/10000.0)*x83;
  const double x85 = x51/x38;
  const double x86 = x41/std::pow(x19, 2);
  const double x87 = x76*x86;
  const double x88 = x39*x87;
  const double x89 = -1.0/40.0*x39*x40*x41;
  const double x90 = x49 + x89;
  const double x91 = (((x90 > 0) ? (
   0
)
: ((x90 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x92 = (1.0/100.0)*x91;
  const double x93 = x45*x47;
  const double x94 = x87*x93;
  const double x95 = 1.0/x17;
  const double x96 = x45*x48*x95;
  const double x97 = x76*x96;
  const double x98 = 2*(((x90 < 0) ? (
   0
)
: ((x90 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x99 = x38*x50*(1 - std::pow(x51, 2));
  const double x100 = std::pow(x53, -2);
  const double x101 = x100*x58*x74;
  const double x102 = x60 + x89;
  const double x103 = (((x102 > 0) ? (
   0
)
: ((x102 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x104 = (1.0/200.0)*x103;
  const double x105 = (((x102 < 0) ? (
   0
)
: ((x102 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x106 = -3.4239999999999999*x15*x17*x39*x69 + x61;
  const double x107 = 4*(((x106 > 0) ? (
   0
)
: ((x106 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x108 = (1.0/5.0)*x67;
  const double x109 = 0.077039999999999997*x62;
  const double x110 = 0.20543999999999998*x64;
  const double x111 = x39*x71*(((x40*x41*x67 - 9.9999999999999995e-21 < 0) ? (
   0
)
: ((x40*x41*x67 - 9.9999999999999995e-21 == 0) ? (
   1.0/2.0
)
: (
   1
))))/std::pow(x68, 2);
  const double x112 = 4*(((x106 < 0) ? (
   0
)
: ((x106 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x113 = 0.046500000000000007*x18*x54*std::pow(x72, 3)*(1 - std::pow(x73, 2));
  const double x114 = x30*x82;
  const double x115 = x1*x6;
  const double x116 = x31*x37;
  const double x117 = x12*x6;
  const double x118 = x31*x36;
  const double x119 = x25*x86;
  const double x120 = x119*x39;
  const double x121 = x119*x93;
  const double x122 = x25*x96;
  const double x123 = x13*x24;
  const double x124 = std::pow(y, -3);
  const double x125 = x40/std::pow(x20, 2);
  const double x126 = -1.0/20.0*x124*x42 - 3.0/500.0*x125*x39;
  const double x127 = x125*x93;
  const double x128 = 1.0/x15;
  const double x129 = -9.0/400.0*x4 - 3.0/40.0;
  const double x130 = 0.024652799999999996*x15;
  const double x131 = 0.015407999999999998*x20;
  return x12*x5*x9 + (9.0/2000.0)*M_PI*x14*x16*x7 + (3.0/5.0)*x16*x31*(x58*x75 + 1.0/20000.0) + 0.089999999999999997*x22 - x26*x76*(x101*(-x76*x80 - x81*(x85*(x32*x84 + x34*x84) + x99*(-x88*x92 + x98*(-4.4444444444444446*x94 + 3.333333333333333*x97)))) - x113*(x107*(-x104*x88 + x105*(-2.2222222222222223*x94 + 1.6666666666666665*x97)) + x112*(1.0271999999999999*M_PI*x1*x15*x39*x69*x7 - x111*(-x108*x87 + x42*(0.082175999999999999*M_PI*x1*x5*x7 - x109*x76 - x110*x32*x83 + 0.20543999999999998*x15*x20*x3*x57*x7*x82)))) + x15*x76*x77) - x27*(x101*(-x25*x80 - x81*(x85*(x114*x115 - x116*x117 + x117*x118) + x99*(-x120*x92 + x98*(-4.4444444444444446*x121 + 3.333333333333333*x122)))) - x113*(x107*(-x104*x120 + x105*(-2.2222222222222223*x121 + 1.6666666666666665*x122)) + x112*(-x111*(-x108*x119 + x42*(0.20543999999999998*x1*x15*x20*x56*x6*x82 - x109*x25 - x110*x115*x29*x82 + 0.082175999999999999*M_PI*x3*x5*x6)) + 1.0271999999999999*M_PI*x15*x3*x39*x6*x69)) + x15*x25*x77) + x27*(x23*x24 + (3.0/10.0)*y + 3.0/20.0) - x5*(0.31*x100*x15*x17*x74*(-x79*(0.014879999999999999*x4 + 0.074399999999999994) - x81*(x85*(x11*x114*x13 - x116*x123 + x118*x123) + x99*(2*x126*x91 + x98*(-5.333333333333333*x127 + 22.222222222222221*x128*x129*x40*x41*x45*x47*x95 - x43*x46)))) - x113*(x107*(x103*x126 + x105*(-2.6666666666666665*x127 + 11.111111111111111*x128*x129*x40*x41*x45*x47*x95 - x43*x59)) + x112*(-x111*(-6.0/25.0*x125*x67 + x42*(x130*x63 + x130*x66 - x131*x63 - x131*x66)) - 6.8479999999999999*x124*x18*x69 - 0.51359999999999995*x17*x70)) - 0.0465*x17*x75) - std::min(1.7999999999999998*x22, x54*x58*(std::pow(x13, 2)*x55*std::pow(x9, 2) + std::pow(x14, 2)*x55*x56 + std::pow(x23, 2)*x55*x57 + 0.089999999999999997));
}
inline double srcw_B_1994(double x, double y, double z) {
  const double x0 = M_PI*x;
  const double x1 = std::sin(x0);
  const double x2 = M_PI*z;
  const double x3 = std::sin(x2);
  const double x4 = x1*x3;
  const double x5 = (6.0/125.0)*x4 + 6.0/25.0;
  const double x6 = std::cos(x0);
  const double x7 = std::cos(x2);
  const double x8 = -x7;
  const double x9 = -x6 - x8;
  const double x10 = M_PI*y;
  const double x11 = std::sin(x10);
  const double x12 = (3.0/200.0)*x11;
  const double x13 = std::cos(x10);
  const double x14 = -x13 + x6;
  const double x15 = (6.0/25.0)*y + 6.0/25.0;
  const double x16 = x15*x4;
  const double x17 = x13 + x8;
  const double x18 = (3.0/200.0)*x1;
  const double x19 = M_PI*x3*x6;
  const double x20 = x15*x19;
  const double x21 = (1.0/5.0)*x20;
  const double x22 = std::pow(x15, 2);
  const double x23 = (1.0/5.0)*x4 + 1;
  const double x24 = std::pow(x23, 2);
  const double x25 = std::pow(y, -2);
  const double x26 = 1.0/x23;
  const double x27 = 1.0/x15;
  const double x28 = x26*x27;
  const double x29 = x25*x28;
  const double x30 = (1.0/40.0)*x29;
  const double x31 = 1.0/y;
  const double x32 = x28*x31;
  const double x33 = 1.0/2.0 - 3.0/20.0*y;
  const double x34 = (3.0/10.0)*x4 + 1;
  const double x35 = x33*x34;
  const double x36 = std::sqrt(x35);
  const double x37 = 11.111111111111111*x36;
  const double x38 = x32*x37;
  const double x39 = std::max(x30, x38);
  const double x40 = -9.0/200.0*x4 - 3.0/20.0;
  const double x41 = x40*x5;
  const double x42 = std::pow(x7, 2);
  const double x43 = std::pow(M_PI, 2);
  const double x44 = std::pow(x1, 2);
  const double x45 = x43*x44;
  const double x46 = x42*x45;
  const double x47 = x15*x33;
  const double x48 = 0.10271999999999999*x47;
  const double x49 = std::pow(x3, 2);
  const double x50 = std::pow(x6, 2);
  const double x51 = x43*x49*x50;
  const double x52 = 1.712*x41 + x46*x48 + x48*x51;
  const double x53 = std::max(9.9999999999999995e-21, x28*x52);
  const double x54 = 1.0/x53;
  const double x55 = x25*x54;
  const double x56 = 3.4239999999999999*x35;
  const double x57 = std::min(x39, x55*x56);
  const double x58 = std::tanh(std::pow(x57, 4));
  const double x59 = (9.0/20000.0)*x43;
  const double x60 = (3.0/50.0)*x47;
  const double x61 = 0.31*x15*x23;
  const double x62 = (9.0/10000.0)*x49;
  const double x63 = std::pow(x11, 2);
  const double x64 = M_PI*x1;
  const double x65 = (3.0/100.0)*x11*x64 - 3.0/10.0;
  const double x66 = -x65;
  const double x67 = std::sqrt(x43*x62*x63 + x45*x62 + (1.0/2.0)*std::pow(x65, 2) + (1.0/2.0)*std::pow(x66, 2) + 1.0e-300);
  const double x68 = 22.222222222222221*x36;
  const double x69 = x32*x68;
  const double x70 = std::max(x30, x69);
  const double x71 = std::tanh(std::pow(x70, 2));
  const double x72 = x67*x71;
  const double x73 = std::max(x61, x72);
  const double x74 = 1.0/x73;
  const double x75 = 0.85599999999999998 - 0.35599999999999998*x58;
  const double x76 = x74*x75;
  const double x77 = 0.31*x35;
  const double x78 = x64*x7;
  const double x79 = 0.092999999999999999*x76;
  const double x80 = x15*x78;
  const double x81 = x61 - x72;
  const double x82 = (((x81 < 0) ? (
   0
)
: ((x81 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x83 = 0.062*x82;
  const double x84 = (((x81 > 0) ? (
   0
)
: ((x81 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x85 = std::pow(M_PI, 3);
  const double x86 = x3*x7*x85;
  const double x87 = (9.0/10000.0)*x86;
  const double x88 = x71/x67;
  const double x89 = x27/x24;
  const double x90 = x78*x89;
  const double x91 = x25*x90;
  const double x92 = -1.0/40.0*x25*x26*x27;
  const double x93 = x69 + x92;
  const double x94 = (((x93 > 0) ? (
   0
)
: ((x93 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x95 = (1.0/100.0)*x94;
  const double x96 = x31*x36;
  const double x97 = x90*x96;
  const double x98 = 1.0/x34;
  const double x99 = x32*x36*x98;
  const double x100 = x78*x99;
  const double x101 = 2*(((x93 < 0) ? (
   0
)
: ((x93 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x102 = x67*x70*(1 - std::pow(x71, 2));
  const double x103 = std::pow(x73, -2);
  const double x104 = x103*x75*x77;
  const double x105 = x38 + x92;
  const double x106 = (((x105 > 0) ? (
   0
)
: ((x105 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x107 = (1.0/200.0)*x106;
  const double x108 = (((x105 < 0) ? (
   0
)
: ((x105 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x109 = -3.4239999999999999*x25*x33*x34*x54 + x39;
  const double x110 = 4*(((x109 > 0) ? (
   0
)
: ((x109 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x111 = (1.0/5.0)*x52;
  const double x112 = 0.077039999999999997*x5;
  const double x113 = 0.20543999999999998*x47;
  const double x114 = x25*x56*(((x26*x27*x52 - 9.9999999999999995e-21 < 0) ? (
   0
)
: ((x26*x27*x52 - 9.9999999999999995e-21 == 0) ? (
   1.0/2.0
)
: (
   1
))))/std::pow(x53, 2);
  const double x115 = 4*(((x109 < 0) ? (
   0
)
: ((x109 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x116 = 0.11036*x35*std::pow(x57, 3)*x74*(1 - std::pow(x58, 2));
  const double x117 = x62*x85;
  const double x118 = x1*x6;
  const double x119 = x43*x66;
  const double x120 = x12*x6;
  const double x121 = x43*x65;
  const double x122 = x19*x89;
  const double x123 = x122*x25;
  const double x124 = x122*x96;
  const double x125 = x19*x99;
  const double x126 = x13*x18;
  const double x127 = std::pow(y, -3);
  const double x128 = x26/x22;
  const double x129 = -1.0/20.0*x127*x28 - 3.0/500.0*x128*x25;
  const double x130 = x128*x96;
  const double x131 = 1.0/x33;
  const double x132 = -9.0/400.0*x4 - 3.0/40.0;
  const double x133 = 0.024652799999999996*x33;
  const double x134 = 0.015407999999999998*x15;
  return x12*x5*x9 + (3.0/1000.0)*M_PI*x14*x16*x7 + (2.0/5.0)*x16*x43*(x76*x77 + 1.0/20000.0) - x21*(x104*(-x20*x83 - x84*(x102*(x101*(-4.4444444444444446*x124 + 3.333333333333333*x125) - x123*x95) + x88*(x117*x118 - x119*x120 + x120*x121))) - x116*(x110*(-x107*x123 + x108*(-2.2222222222222223*x124 + 1.6666666666666665*x125)) + x115*(-x114*(-x111*x122 + x28*(0.20543999999999998*x1*x15*x33*x42*x6*x85 - x112*x19 - x113*x118*x49*x85 + 0.082175999999999999*M_PI*x3*x40*x6)) + 1.0271999999999999*M_PI*x25*x3*x33*x54*x6)) + x19*x33*x79) + x21*(x17*x18 + (3.0/10.0)*y + 3.0/20.0) + x22*x24*(0.082799999999999999 - 0.0078000000000000014*x58) - x28*(1.712 - 1.712*x58)*(x41 + x46*x60 + x51*x60) - x5*(0.31*x103*x33*x34*x75*(-x82*(0.014879999999999999*x4 + 0.074399999999999994) - x84*(x102*(x101*(-5.333333333333333*x130 + 22.222222222222221*x131*x132*x26*x27*x31*x36*x98 - x29*x68) + 2*x129*x94) + x88*(x11*x117*x13 - x119*x126 + x121*x126))) - x116*(x110*(x106*x129 + x108*(-2.6666666666666665*x130 + 11.111111111111111*x131*x132*x26*x27*x31*x36*x98 - x29*x37)) + x115*(-x114*(-6.0/25.0*x128*x52 + x28*(x133*x46 + x133*x51 - x134*x46 - x134*x51)) - 6.8479999999999999*x127*x35*x54 - 0.51359999999999995*x34*x55)) - 0.0465*x34*x76) - 1.0/5.0*x80*(x104*(-x80*x83 - x84*(x102*(x101*(3.333333333333333*x100 - 4.4444444444444446*x97) - x91*x95) + x88*(x44*x87 + x63*x87))) - x116*(x110*(-x107*x91 + x108*(1.6666666666666665*x100 - 2.2222222222222223*x97)) + x115*(1.0271999999999999*M_PI*x1*x25*x33*x54*x7 - x114*(-x111*x90 + x28*(0.082175999999999999*M_PI*x1*x40*x7 - x112*x78 - x113*x44*x86 + 0.20543999999999998*x15*x3*x33*x50*x7*x85)))) + x33*x78*x79) - 1.0*(0.11281200000000008*x58 + 0.44035466666666673)*(std::pow(x13, 2)*x59*std::pow(x9, 2) + std::pow(x14, 2)*x42*x59 + std::pow(x17, 2)*x50*x59 + 0.089999999999999997);
}
inline double srcu0_B_1994(double x, double y, double z) {
  const double x0 = M_PI*x;
  const double x1 = std::sin(x0);
  const double x2 = M_PI*z;
  const double x3 = std::sin(x2);
  const double x4 = std::pow(x3, 2);
  const double x5 = std::cos(x0);
  const double x6 = M_PI*y;
  const double x7 = std::cos(x6);
  const double x8 = (3.0/200.0)*x1;
  const double x9 = std::sin(x6);
  const double x10 = M_PI*x9;
  const double x11 = -std::cos(x2);
  const double x12 = (3.0/200.0)*x9;
  const double x13 = x11 + x7;
  const double x14 = M_PI*x5;
  const double x15 = x13*x14;
  const double x16 = x1*x3;
  const double x17 = (3.0/10.0)*x16 + 1;
  const double x18 = (6.0/25.0)*y + 6.0/25.0;
  const double x19 = (1.0/5.0)*x16 + 1;
  const double x20 = 0.31*x18*x19;
  const double x21 = std::pow(M_PI, 2);
  const double x22 = (9.0/10000.0)*x4;
  const double x23 = x21*x22;
  const double x24 = (3.0/100.0)*x1;
  const double x25 = x10*x24 - 3.0/10.0;
  const double x26 = -x25;
  const double x27 = std::sqrt(std::pow(x1, 2)*x23 + x23*std::pow(x9, 2) + (1.0/2.0)*std::pow(x25, 2) + (1.0/2.0)*std::pow(x26, 2) + 1.0e-300);
  const double x28 = 1.0/x18;
  const double x29 = std::pow(y, -2);
  const double x30 = 1.0/x19;
  const double x31 = x29*x30;
  const double x32 = x28*x31;
  const double x33 = (1.0/40.0)*x32;
  const double x34 = 1.0/2.0 - 3.0/20.0*y;
  const double x35 = x17*x34;
  const double x36 = std::sqrt(x35);
  const double x37 = 22.222222222222221*x36;
  const double x38 = 1.0/y;
  const double x39 = x28*x30;
  const double x40 = x38*x39;
  const double x41 = x37*x40;
  const double x42 = std::max(x33, x41);
  const double x43 = std::tanh(std::pow(x42, 2));
  const double x44 = std::max(x20, x27*x43);
  const double x45 = 1.0/x44;
  const double x46 = 0.31*x35;
  const double x47 = std::pow(x44, -2);
  const double x48 = x20 - x27*x43;
  const double x49 = (((x48 < 0) ? (
   0
)
: ((x48 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x50 = (((x48 > 0) ? (
   0
)
: ((x48 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x51 = std::pow(M_PI, 3)*x22;
  const double x52 = x21*x26;
  const double x53 = x7*x8;
  const double x54 = x21*x25;
  const double x55 = x43/x27;
  const double x56 = std::pow(x18, -2);
  const double x57 = -x33 + x41;
  const double x58 = (((x57 > 0) ? (
   0
)
: ((x57 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x59 = x36*x38;
  const double x60 = 1.0/x17;
  const double x61 = 2*(((x57 < 0) ? (
   0
)
: ((x57 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x62 = x27*x42*(1 - std::pow(x43, 2));
  const double x63 = x14*x3;
  const double x64 = x12*x5;
  const double x65 = x28*x63/std::pow(x19, 2);
  return (9.0/40000.0)*M_PI*x1*x4*(x5 - x7) + x12*(-x11 - x5)*(-x10*x8 + 3.0/10.0) + x13*x21*x24*(x45*x46 + 1.0/20000.0) - 3.0/100.0*x15*(0.092999999999999999*x34*x45*x63 + x46*x47*(-0.062*x18*x49*x63 - x50*(x55*(x1*x5*x51 - x52*x64 + x54*x64) + x62*(-1.0/100.0*x29*x58*x65 + x61*(3.333333333333333*x36*x40*x60*x63 - 4.4444444444444446*x59*x65))))) + (3.0/200.0)*x15*(x13*x8 + (3.0/10.0)*y + 3.0/20.0) + 0.013949999999999999*x17*x45 - 0.092999999999999999*x35*x47*(-x49*(0.014879999999999999*x16 + 0.074399999999999994) - x50*(x55*(x51*x7*x9 - x52*x53 + x53*x54) + x62*(2*x58*(-3.0/500.0*x31*x56 - 1.0/20.0*x39/std::pow(y, 3)) + x61*(22.222222222222221*x28*x30*x36*x38*x60*(-9.0/400.0*x16 - 3.0/40.0)/x34 - 5.333333333333333*x30*x56*x59 - x32*x37))));
}
inline double srcu1_B_1994(double x, double y, double z) {
  const double x0 = M_PI*y;
  const double x1 = std::sin(x0);
  const double x2 = std::cos(x0);
  const double x3 = M_PI*x;
  const double x4 = std::cos(x3);
  const double x5 = M_PI*z;
  const double x6 = -std::cos(x5);
  const double x7 = -x4 - x6;
  const double x8 = std::sin(x5);
  const double x9 = std::pow(x8, 2);
  const double x10 = M_PI*x1;
  const double x11 = std::sin(x3);
  const double x12 = (3.0/200.0)*x11;
  const double x13 = 1.0/2.0 - 3.0/20.0*y;
  const double x14 = (6.0/25.0)*y + 6.0/25.0;
  const double x15 = x11*x8;
  const double x16 = (1.0/5.0)*x15 + 1;
  const double x17 = 0.31*x14*x16;
  const double x18 = std::pow(M_PI, 2);
  const double x19 = (9.0/10000.0)*x9;
  const double x20 = x18*x19;
  const double x21 = (3.0/100.0)*x10*x11 - 3.0/10.0;
  const double x22 = -x21;
  const double x23 = std::sqrt(std::pow(x1, 2)*x20 + std::pow(x11, 2)*x20 + (1.0/2.0)*std::pow(x21, 2) + (1.0/2.0)*std::pow(x22, 2) + 1.0e-300);
  const double x24 = 1.0/x14;
  const double x25 = std::pow(y, -2);
  const double x26 = 1.0/x16;
  const double x27 = x25*x26;
  const double x28 = x24*x27;
  const double x29 = (3.0/10.0)*x15 + 1;
  const double x30 = x13*x29;
  const double x31 = std::sqrt(x30);
  const double x32 = 22.222222222222221*x31;
  const double x33 = 1.0/y;
  const double x34 = x24*x26;
  const double x35 = x33*x34;
  const double x36 = x32*x35;
  const double x37 = std::max(x36, (1.0/40.0)*x28);
  const double x38 = std::tanh(std::pow(x37, 2));
  const double x39 = x23*x38;
  const double x40 = std::max(x17, x39);
  const double x41 = 1.0/x40;
  const double x42 = M_PI*x4*x8;
  const double x43 = 0.31*x30;
  const double x44 = std::pow(x40, -2);
  const double x45 = x17 - x39;
  const double x46 = (((x45 < 0) ? (
   0
)
: ((x45 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x47 = (((x45 > 0) ? (
   0
)
: ((x45 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x48 = std::pow(M_PI, 3)*x19;
  const double x49 = x18*x22;
  const double x50 = (3.0/200.0)*x1*x4;
  const double x51 = x18*x21;
  const double x52 = x38/x23;
  const double x53 = -1.0/40.0*x24*x25*x26 + x36;
  const double x54 = (((x53 > 0) ? (
   0
)
: ((x53 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x55 = x24*x42/std::pow(x16, 2);
  const double x56 = x31*x33;
  const double x57 = 1.0/x29;
  const double x58 = 2*(((x53 < 0) ? (
   0
)
: ((x53 == 0) ? (
   1.0/2.0
)
: (
   1
))));
  const double x59 = x23*x37*(1 - std::pow(x38, 2));
  const double x60 = x12*x2;
  const double x61 = std::pow(x14, -2);
  return (3.0/200.0)*M_PI*x1*x11*(x12*(x2 + x6) + (3.0/10.0)*y + 3.0/20.0) + (3.0/100.0)*x1*x18*x7*(x41*x43 + 1.0/20000.0) + (9.0/40000.0)*M_PI*x1*x2*std::pow(x7, 2) - 9.0/40000.0*x10*x9*(-x2 + x4) - 0.027899999999999998*x13*x41*x42 - 3.0/100.0*M_PI*x2*x7*(-0.0465*x29*x41 + x43*x44*(-x46*(0.014879999999999999*x15 + 0.074399999999999994) - x47*(x52*(x1*x2*x48 - x49*x60 + x51*x60) + x59*(2*x54*(-3.0/500.0*x27*x61 - 1.0/20.0*x34/std::pow(y, 3)) + x58*(-5.333333333333333*x26*x56*x61 - x28*x32 + 22.222222222222221*x24*x26*x31*x33*x57*(-9.0/400.0*x15 - 3.0/40.0)/x13))))) - 0.092999999999999999*x30*x44*(-0.062*x14*x42*x46 - x47*(x52*(x11*x4*x48 - x49*x50 + x50*x51) + x59*(-1.0/100.0*x25*x54*x55 + x58*(3.333333333333333*x31*x35*x42*x57 - 4.4444444444444446*x55*x56))));
}
inline double srcu2_B_1994(double x, double y, double z) {
  const double x0 = M_PI*z;
  const double x1 = std::sin(x0);
  const double x2 = M_PI*y;
  const double x3 = std::sin(x2);
  const double x4 = std::pow(x3, 2);
  const double x5 = M_PI*x;
  const double x6 = std::cos(x5);
  const double x7 = std::cos(x0);
  const double x8 = -x7;
  const double x9 = (9.0/40000.0)*M_PI;
  const double x10 = std::cos(x2);
  const double x11 = -x10 + x6;
  const double x12 = x1*x7;
  const double x13 = std::sin(x5);
  const double x14 = x1*x13;
  const double x15 = std::pow(M_PI, 2);
  const double x16 = (6.0/25.0)*y + 6.0/25.0;
  const double x17 = (1.0/5.0)*x14 + 1;
  const double x18 = 0.31*x16*x17;
  const double x19 = (9.0/10000.0)*std::pow(x13, 2);
  const double x20 = std::pow(x1, 2)*x15;
  const double x21 = (9.0/10000.0)*x4;
  const double x22 = (3.0/100.0)*M_PI;
  const double x23 = x13*x22*x3 - 3.0/10.0;
  const double x24 = std::sqrt(x19*x20 + x20*x21 + std::pow(x23, 2) + 1.0e-300);
  const double x25 = std::pow(y, -2);
  const double x26 = 1.0/x16;
  const double x27 = x26/x17;
  const double x28 = (1.0/40.0)*x25*x27;
  const double x29 = 1.0/2.0 - 3.0/20.0*y;
  const double x30 = (3.0/10.0)*x14 + 1;
  const double x31 = x29*x30;
  const double x32 = std::sqrt(x31)/y;
  const double x33 = x27*x32;
  const double x34 = 22.222222222222221*x33;
  const double x35 = std::max(x28, x34);
  const double x36 = std::tanh(std::pow(x35, 2));
  const double x37 = std::max(x18, x24*x36);
  const double x38 = 1.0/x37;
  const double x39 = 0.31*x31;
  const double x40 = M_PI*x13*x7;
  const double x41 = x18 - x24*x36;
  const double x42 = std::pow(M_PI, 3)*x12;
  const double x43 = -x28 + x34;
  const double x44 = x26*x40/std::pow(x17, 2);
  return (3.0/100.0)*x1*x11*x15*(x38*x39 + 1.0/20000.0) + x1*x4*x9*(-x6 - x8) + std::pow(x11, 2)*x12*x9 - x11*x22*x7*(0.092999999999999999*x29*x38*x40 + x39*(-0.062*x16*x40*(((x41 < 0) ? (
   0
)
: ((x41 == 0) ? (
   1.0/2.0
)
: (
   1
)))) - (x24*x35*(1 - std::pow(x36, 2))*(-1.0/100.0*x25*x44*(((x43 > 0) ? (
   0
)
: ((x43 == 0) ? (
   1.0/2.0
)
: (
   1
)))) + 2*(-4.4444444444444446*x32*x44 + 3.333333333333333*x33*x40/x30)*(((x43 < 0) ? (
   0
)
: ((x43 == 0) ? (
   1.0/2.0
)
: (
   1
))))) + x36*(x19*x42 + x21*x42)/x24)*(((x41 > 0) ? (
   0
)
: ((x41 == 0) ? (
   1.0/2.0
)
: (
   1
)))))/std::pow(x37, 2)) - 3.0/200.0*M_PI*x14*((3.0/200.0)*x13*(x10 + x8) + (3.0/10.0)*y + 3.0/20.0);
}
inline constexpr double nu_B = 5e-05;

}  // namespace vibeflow::sst_ms
