"""
Manufactured solutions for the k-omega SST model (ADR-042, gate 2).

The model's formulas are written here once, in sympy, for both variants, and
applied to two exact states on the unit cube with a wall at y = 0 (so the wall
distance is d = y exactly):

  MS-A  blending on, eddy-viscosity limiter off
  MS-B  eddy-viscosity limiter on everywhere (F1 = F2 = 1)

Why two: the limiter max(a1 w, S F2) cannot switch on and off inside the
domain without a kink in nu_t, and no scheme converges through a kink at
second order (Eca et al., IST report D72-34). Each solution keeps every
switch of the model on one side wherever it matters -- F1 = tanh(arg1^4) and
F2 = tanh(arg2^2) are saturated (1 to 1e-14) wherever their max/min change
branch -- and check() verifies that on the exact fields at the points it is
given, which the gates call with each mesh's cell centres.

The same expressions give the sources the Python gates add (numpy) and the
C++ gates add (C code, generated by c_source()).

Momentum: the full stress, div[(nu + nu_t)(grad u + grad u^T)]; the flow is
incompressible, so the production P = tau_ij du_i/dx_j is exactly nu_t S^2
and the isotropic (2/3)k is carried by the pressure.
"""

import functools

import numpy as np
import sympy as sp

X = sp.symbols("x y z", real=True)
x, y, z = X

# Constants common to both variants (TMR's tables for SST and SST-2003).
SIGMA_K1, SIGMA_W1, BETA1 = 0.85, 0.5, 0.075
SIGMA_K2, SIGMA_W2, BETA2 = 1.0, 0.856, 0.0828
BETA_STAR, KAPPA, A1 = 0.09, 0.41, 0.31


def variant_constants(variant):
    """gamma_1, gamma_2, the CD_kw floor, the production limiter's factor,
    whether the omega production is limited, and whether the eddy viscosity
    uses the vorticity (1994) or the strain rate (2003)."""
    if variant == "2003":
        return dict(g1=5.0 / 9.0, g2=0.44, cd_floor=1e-10, plim=10.0,
                    limit_w_production=True, use_vorticity=False)
    if variant == "1994":
        rb = np.sqrt(BETA_STAR)
        return dict(g1=BETA1 / BETA_STAR - SIGMA_W1 * KAPPA ** 2 / rb,
                    g2=BETA2 / BETA_STAR - SIGMA_W2 * KAPPA ** 2 / rb,
                    cd_floor=1e-20, plim=20.0,
                    limit_w_production=False, use_vorticity=True)
    raise ValueError(variant)


# ------------------------------------------------------------ the two states
def _solenoidal():
    s, c, pi = sp.sin, sp.cos, sp.pi
    u = [s(pi*x)*(c(pi*y) - c(pi*z)), s(pi*y)*(c(pi*z) - c(pi*x)),
         s(pi*z)*(c(pi*x) - c(pi*y))]
    a = [s(pi*y)*s(pi*z)/pi, s(pi*z)*s(pi*x)/pi, s(pi*x)*s(pi*y)/pi]   # curl a = u
    return u, a


def state(name):
    """Velocity, its vector potential, pressure, k, omega and nu for MS-A or
    MS-B, as sympy expressions."""
    s, c, pi = sp.sin, sp.cos, sp.pi
    su, sa = _solenoidal()
    # ADR-042's revision: k and omega vary as sin(pi x) sin(pi z) and linearly
    # in y, so their normal curvature vanishes on every face -- the one-sided
    # boundary flux then carries no O(1) truncation error into the first
    # cell, which on these meshes the reaction term would not let diffusion
    # suppress.
    if name == "A":
        U0 = sp.Rational(1, 10)
        u = [U0 * e for e in su]
        a = [U0 * e for e in sa]
        p = sp.Rational(1, 100) * c(pi*x) * c(pi*y) * c(pi*z)
        k = sp.Rational(1, 10) * (sp.Rational(1, 2) + y) * (1 + sp.Rational(3, 10)*s(pi*x)*s(pi*z))
        w = 5 * (sp.Rational(3, 2) - y/2) * (1 + sp.Rational(1, 5)*s(pi*x)*s(pi*z))
        nu = sp.Rational(5, 100000)
    elif name == "B":
        # A linear shear, whose least-squares gradient is exact, plus a small
        # solenoidal part; slow enough that diffusion outweighs the k
        # equation's net production, which the limiter-on state has.
        U0, eps = sp.Rational(3, 10), sp.Rational(3, 200)
        u = [U0*(sp.Rational(1, 2) + y) + eps*su[0], eps*su[1], eps*su[2]]
        # curl (0, 0, U0 (y/2 + y^2/2)) = (U0 (1/2 + y), 0, 0)
        a = [eps*sa[0], eps*sa[1], U0*(y/2 + y**2/2) + eps*sa[2]]
        p = sp.Integer(0)
        k = sp.Rational(1, 2) * (1 - sp.Rational(3, 10)*y) * (1 + sp.Rational(3, 10)*s(pi*x)*s(pi*z))
        w = sp.Rational(6, 25) * (1 + y) * (1 + sp.Rational(1, 5)*s(pi*x)*s(pi*z))
        nu = sp.Rational(5, 100000)
    else:
        raise ValueError(name)
    curl = [sp.diff(a[2], y) - sp.diff(a[1], z), sp.diff(a[0], z) - sp.diff(a[2], x),
            sp.diff(a[1], x) - sp.diff(a[0], y)]
    assert all(sp.simplify(curl[i] - u[i]) == 0 for i in range(3))
    assert sp.simplify(sum(sp.diff(u[i], X[i]) for i in range(3))) == 0
    return dict(u=u, a=a, p=p, k=k, w=w, nu=nu)


# ------------------------------------------------------------ the model
def model_terms(st, variant):
    """Every quantity of the SST model for the exact state, as sympy."""
    cst = variant_constants(variant)
    u, k, w, nu = st["u"], st["k"], st["w"], st["nu"]
    d = y                                     # the wall is y = 0
    G = [[sp.diff(u[i], X[j]) for j in range(3)] for i in range(3)]
    # The 1e-300 changes nothing the solver would see, but keeps the
    # derivative of an inactive max() branch finite where S or Omega is zero:
    # sympy writes it as Heaviside(...) * S', and S' = (S^2)'/(2S) is 0/0 there.
    S = sp.sqrt(sum((G[i][j] + G[j][i])**2 for i in range(3) for j in range(3)) / 2
                + sp.Float(1e-300))
    Om = sp.sqrt(sum((G[i][j] - G[j][i])**2 for i in range(3) for j in range(3)) / 2
                 + sp.Float(1e-300))
    gk = [sp.diff(k, v) for v in X]
    gw = [sp.diff(w, v) for v in X]
    kw = sum(gk[i]*gw[i] for i in range(3))
    brA = sp.sqrt(k) / (BETA_STAR * w * d)
    brB = 500 * nu / (d**2 * w)
    CD = sp.Max(2 * SIGMA_W2 * kw / w, cst["cd_floor"])
    brC = 4 * SIGMA_W2 * k / (CD * d**2)
    arg1 = sp.Min(sp.Max(brA, brB), brC)
    F1 = sp.tanh(arg1**4)
    brA2 = 2 * sp.sqrt(k) / (BETA_STAR * w * d)
    arg2 = sp.Max(brA2, brB)
    F2 = sp.tanh(arg2**2)
    V = Om if cst["use_vorticity"] else S
    nut = A1 * k / sp.Max(A1 * w, V * F2)
    P = nut * S**2
    Pk = sp.Min(P, cst["plim"] * BETA_STAR * w * k)

    def blend(a, b):
        return F1 * a + (1 - F1) * b
    sk, sw = blend(SIGMA_K1, SIGMA_K2), blend(SIGMA_W1, SIGMA_W2)
    beta, gamma = blend(BETA1, BETA2), blend(cst["g1"], cst["g2"])
    Pw = gamma * (Pk if cst["limit_w_production"] else P) / nut

    conv_k = sum(u[j] * gk[j] for j in range(3))
    conv_w = sum(u[j] * gw[j] for j in range(3))
    diff_k = sum(sp.diff((nu + sk * nut) * gk[j], X[j]) for j in range(3))
    diff_w = sum(sp.diff((nu + sw * nut) * gw[j], X[j]) for j in range(3))
    cross = 2 * (1 - F1) * SIGMA_W2 * kw / w
    src_k = conv_k - Pk + BETA_STAR * w * k - diff_k
    src_w = conv_w - Pw + beta * w**2 - diff_w - cross
    src_u = []
    for i in range(3):
        conv = sum(u[j] * G[i][j] for j in range(3))
        visc = sum(sp.diff((nu + nut) * (G[i][j] + G[j][i]), X[j]) for j in range(3))
        src_u.append(conv - visc + sp.diff(st["p"], X[i]))
    return dict(S=S, Om=Om, kw=kw, brA=brA, brB=brB, brC=brC, arg1=arg1, F1=F1,
                brA2=brA2, arg2=arg2, F2=F2, nut=nut, P=P, Pk=Pk, V=V,
                src_k=src_k, src_w=src_w, src_u=src_u)


_NUMPY = [{"Max": lambda *a: functools.reduce(np.maximum, a),
           "Min": lambda *a: functools.reduce(np.minimum, a),
           "Heaviside": lambda v, h=0.5: np.heaviside(v, h)}, "numpy"]


def _lam(expr):
    f = sp.lambdify(X, expr, modules=_NUMPY, cse=True)

    def g(q):
        # Inactive branches of max() and min() may overflow or divide by zero
        # where they are not selected; the selected value is finite.
        with np.errstate(all="ignore"):
            v = f(q[:, 0], q[:, 1], q[:, 2])
        return np.broadcast_to(np.asarray(v, float), (len(q),)).copy()
    return g


@functools.lru_cache(maxsize=None)
def numeric(name, variant):
    """numpy callables on (n, 3) points: exact fields, sources, and the model
    quantities check() inspects."""
    st = state(name)
    t = model_terms(st, variant)
    out = {"nu": float(st["nu"])}
    for key in ("k", "w", "p"):
        out[key] = _lam(st[key])
    uf = [_lam(e) for e in st["u"]]
    af = [_lam(e) for e in st["a"]]
    out["u"] = lambda q: np.column_stack([f(q) for f in uf])
    out["a"] = lambda q: np.column_stack([f(q) for f in af])
    su = [_lam(e) for e in t["src_u"]]
    out["src_u"] = lambda q: np.column_stack([f(q) for f in su])
    for key in ("src_k", "src_w", "S", "Om", "brA", "brB", "brC", "arg1", "F1",
                "brA2", "arg2", "F2", "nut", "P", "Pk", "V"):
        out[key] = _lam(t[key])
    return out


def check(name, variant, q):
    """The properties ADR-042 requires of each solution, at the points q.
    Returns (ok, one line of margins)."""
    f = numeric(name, variant)
    cst = variant_constants(variant)
    A, B, C = f["brA"](q), f["brB"](q), f["brC"](q)
    arg1 = f["arg1"](q)
    unsat1 = arg1 < 2.0                        # tanh(16) = 1 - 2.5e-14
    a_active = np.allclose(arg1[unsat1], A[unsat1], rtol=1e-12, atol=0.0)
    m_ab = np.min(A[unsat1] / B[unsat1]) if unsat1.any() else np.inf
    m_ca = np.min(C[unsat1] / A[unsat1]) if unsat1.any() else np.inf
    arg2 = f["arg2"](q)
    unsat2 = arg2 < 4.0                        # tanh(16)
    A2 = f["brA2"](q)
    a2_active = np.allclose(arg2[unsat2], A2[unsat2], rtol=1e-12, atol=0.0)
    m_ab2 = np.min(A2[unsat2] / B[unsat2]) if unsat2.any() else np.inf
    w, k = f["w"](q), f["k"](q)
    VF2 = f["V"](q) * f["F2"](q)
    P = f["P"](q)
    p_ratio = np.max(P / (cst["plim"] * BETA_STAR * w * k))
    F1 = f["F1"](q)
    ok = a_active and a2_active and m_ab > 5 and m_ca > 5 and m_ab2 > 5 and p_ratio < 0.9
    if name == "A":
        lim = np.min(A1 * w / np.maximum(VF2, 1e-300))   # > 1: limiter off
        ok &= lim > 1.1
        lim_txt = f"a1 w / V F2 >= {lim:.2f}"
    else:
        lim = np.min(VF2 / (A1 * w))           # > 1: limiter on
        ok &= lim > 1.1
        lim_txt = f"V F2 / a1 w >= {lim:.2f}"
    line = (f"F1 in [{F1.min():.3f}, {F1.max():.3f}], arg1 branch 1 where unsaturated "
            f"({m_ab:.1f}x branch 2, {m_ca:.1f}x branch 3), arg2 branch 1 where unsaturated "
            f"({m_ab2:.1f}x), {lim_txt}, P/limit <= {p_ratio:.2f}")
    return bool(ok), line


def c_source(names=("A", "B"), variants=("2003", "1994")):
    """C++ header with the exact fields and sources, from the same
    expressions, for the C++ gates."""
    lines = ["#pragma once",
             "// Generated by prototype/sst_ms.py (c_source); do not edit.",
             "// Exact fields and manufactured sources of ADR-042's MS-A and MS-B.",
             "#include <algorithm>", "#include <cmath>", "",
             "namespace vibeflow::sst_ms {", ""]
    helpers = ["inline double Max(double a, double b) { return std::max(a, b); }",
               "inline double Min(double a, double b) { return std::min(a, b); }",
               "inline double Heaviside(double v) { return v > 0 ? 1.0 : (v < 0 ? 0.0 : 0.5); }",
               ""]
    lines += helpers
    from sympy.printing.cxx import CXX11CodePrinter
    printer = CXX11CodePrinter()

    def emit(fname, expr):
        reps, red = sp.cse(expr)
        body = [f"inline double {fname}(double x, double y, double z) {{"]
        for sym, e in reps:
            body.append(f"  const double {sym} = {printer.doprint(e)};")
        body.append(f"  return {printer.doprint(red[0])};")
        body.append("}")
        return body

    for name in names:
        st = state(name)
        for key in ("k", "w", "p"):
            lines += emit(f"{key}_{name}", st[key])
        for i in range(3):
            lines += emit(f"u{i}_{name}", st["u"][i])
            lines += emit(f"a{i}_{name}", st["a"][i])
        for variant in variants:
            t = model_terms(st, variant)
            v = variant
            lines += emit(f"srck_{name}_{v}", t["src_k"])
            lines += emit(f"srcw_{name}_{v}", t["src_w"])
            for i in range(3):
                lines += emit(f"srcu{i}_{name}_{v}", t["src_u"][i])
        lines.append(f"inline constexpr double nu_{name} = {float(st['nu'])!r};")
        lines.append("")
    lines += ["}  // namespace vibeflow::sst_ms", ""]
    return "\n".join(l.replace("std::Max", "Max").replace("std::Min", "Min") for l in lines)


if __name__ == "__main__":
    import sys
    if len(sys.argv) == 3 and sys.argv[1] == "--header":
        with open(sys.argv[2], "w") as fh:
            fh.write(c_source())
        sys.exit(0)
    if len(sys.argv) == 3 and sys.argv[1] == "--check-header":
        # The committed header must be what these formulas generate now.
        same = open(sys.argv[2]).read() == c_source()
        print("generated header up to date" if same else "generated header STALE: regenerate it")
        sys.exit(0 if same else 1)
    g = np.linspace(1 / 82, 1 - 1 / 82, 41)
    q = np.stack(np.meshgrid(g, g, g, indexing="ij"), axis=-1).reshape(-1, 3)
    for name in ("A", "B"):
        for variant in ("2003", "1994"):
            ok, line = check(name, variant, q)
            print(f"MS-{name} SST-{variant}: {'ok' if ok else 'VIOLATED'}  {line}")
